import type { Catalog } from "../../shared/i18n/catalog";
import type { Evidence, RulesSource, UnavailableReason } from "./types";

/**
 * Wording rule (ADR 0003): results describe what was observed and never
 * certify a file or device, in every language. Spanish avoids "seguro",
 * "limpio", "protegido" and "certificado" in result wording for the same reason.
 */
const en = {
  layout: {
    eyebrow: "Diagnostics",
    title: "Protection",
    intro: "Checks files and processes on this PC using signed rules and local heuristics. It works offline and complements your antivirus; it does not replace it.",
    navLabel: "Protection sections",
    sections: {
      overview: "Overview",
      scan: "Scan",
      processes: "Processes",
      quarantine: "Quarantine",
      rules: "Rules",
      breach: "Password check",
    },
  },
  evidenceKind: {
    deterministic: "Signed-rule match",
    heuristic: "Heuristic",
    unavailable: "Not checked",
    external: "External response",
  } satisfies Record<Evidence["kind"], string>,
  evidenceHint: {
    deterministic: "Matched a hash or byte pattern in a signed rule pack.",
    heuristic: "A local pattern that is often suspicious. It can be a false positive.",
    unavailable: "This item could not be examined. That is not the same as no match.",
    external: "Reported by a component this app does not control.",
  } satisfies Record<Evidence["kind"], string>,
  unavailable: {
    accessDenied: "Access denied",
    inUse: "In use by another program",
    tooLarge: "Larger than the scan limit",
    reparsePoint: "Link or junction, not followed",
    notFound: "No longer exists",
    signerNotCheckable: "Signature could not be checked",
    providerAbsent: "No provider available",
    providerNoResponse: "Provider gave no answer",
    cancelled: "Cancelled",
    readFailed: "Could not be read",
  } satisfies Record<UnavailableReason, string>,
  deterministicDetail: (ruleName: string, ruleId: string, pack: string, exactHash: boolean) =>
    `${ruleName} (rule ${ruleId}, pack ${pack}, ${exactHash ? "exact hash" : "byte pattern"})`,
  signer: {
    signedBy: (subject: string) => `Signed: ${subject}`,
    signed: "Signed",
    unsigned: "No embedded signature",
    invalid: "Signature invalid",
    unavailable: "Signature not checked",
    notApplicable: "Not a signable file",
  },
  summary: {
    examined: (files: string, pack: string) => `${files} files examined with rule pack ${pack}`,
    noSignedMatches: "no signed-rule matches",
    signedMatches: (count: string) => `${count} signed-rule matches`,
    heuristicFindings: (count: string) => `${count} heuristic findings`,
    notChecked: (count: string) => `${count} items not checked`,
  },
  rulesSource: {
    installed: "Installed pack",
    previousFallback: "Previous pack (the newest pack failed verification)",
    embeddedBaseline: "Built-in baseline pack",
  } satisfies Record<RulesSource, string>,
  loading: "Loading…",
  errors: {
    actionFailed: "The action could not be completed.",
  },
  overview: {
    loadFailed: "Protection status could not be read.",
    saveFailed: "The setting could not be saved.",
    defenderFailed: "Defender history could not be read.",
    loading: "Loading protection status…",
    statusTitle: "Status",
    rules: "Rules",
    rulesValue: (source: string, sequence: string, count: string) => `${source}: sequence ${sequence}, ${count} rules`,
    lastScan: "Last scan",
    noScan: "No scan yet",
    quarantine: "Quarantine",
    quarantineItems: (count: string) => `${count} items`,
    networkTitle: "Network use",
    networkIntro: "Everything below is off by default. Scanning always runs on this PC without the network.",
    networkLegend: "Optional features that send data",
    ruleDownload: "Allow downloading signed rule packs",
    ruleDownloadHint: "Contacts raw.githubusercontent.com only when you press Download. Sends no information about your files.",
    breachCheck: "Allow the password breach check",
    breachCheckHint: "Sends only the first 5 characters of the password's SHA-1 hash to api.pwnedpasswords.com. The password itself never leaves this PC.",
    amsi: "Ask the installed antivirus about flagged files (AMSI)",
    amsiHint: "Your antivirus may use its own cloud service for this, depending on its settings.",
    defenderTitle: "Microsoft Defender history",
    defenderIntro: "Reads what Defender has already recorded. This does not start a Defender scan.",
    readHistory: "Read detection history",
    readingHistory: "Reading Defender history…",
    defenderUnavailable: (detail: string) => `${detail}. Defender may not be the active antivirus.`,
    noDetections: "Defender has no recorded detections.",
    threat: (id: string) => `Threat ${id}`,
    unknownThreat: "unknown",
    firstSeen: (when: string) => `, first seen ${when}`,
    truncated: "Showing the first 500 recorded detections.",
    heuristicsTitle: "Heuristics and their limits",
    falsePositives: (note: string) => `False positives: ${note}`,
  },
  scan: {
    failed: "The scan could not run.",
    quarantined: (path: string) => `Moved to quarantine: ${path}`,
    allowed: "Heuristic findings for this exact file content will be hidden in future scans.",
    startTitle: "Start a scan",
    startIntro: "Quick scan checks startup folders, Temp, Downloads and running programs. Folder scan checks one folder you choose. Links and junctions are never followed.",
    quick: "Quick scan",
    folder: "Scan a folder…",
    cancel: "Cancel scan",
    scanning: "Scanning…",
    filesExamined: (count: string) => ` ${count} files examined`,
    resultsTitle: "Results",
    allowlisted: (count: string) => ` · ${count} hidden by your allowlist`,
    reparseSkipped: (count: string) => ` · ${count} links or junctions skipped (not followed)`,
    cancelled: "The scan was cancelled; results are partial.",
    truncated: "The scan stopped at its size limit; results are partial.",
    limitsHint: "A file with no findings has only been compared with the current rules and heuristics. Detection is limited; see the Rules section.",
    falsePositives: (note: string) => `False positives: ${note}`,
    quarantine: "Quarantine…",
    hide: "Hide for this file",
    showingFirst: (shown: string, total: string) => `Showing the first ${shown} of ${total}.`,
  },
  processes: {
    loadFailed: "The process list could not be read.",
    title: "Running processes",
    intro: "Read-only. This app never ends or changes processes; use Task Manager for that. Command lines are not read.",
    refresh: "Refresh",
    filter: "Filter",
    loading: "Reading processes…",
    count: (count: string) => `${count} processes`,
    imageUnavailable: (count: string) => ` · ${count} could not be inspected (usually system or other users' processes)`,
    truncated: " · list truncated",
    columns: { name: "Name", pid: "PID", parent: "Parent", signature: "Signature", findings: "Findings" },
    none: "None",
  },
  quarantine: {
    loadFailed: "The quarantine could not be read.",
    collision: "A file already exists at the original location, so nothing was restored or overwritten. Move or rename that file, then try again.",
    restored: (path: string) => `Restored to ${path}`,
    deleted: "Deleted permanently.",
    title: "Quarantine",
    intro: "Quarantined files are stored in a scrambled form so they cannot run. Restoring never overwrites an existing file. Each action asks for confirmation in a Windows dialog.",
    empty: "The quarantine is empty.",
    unknownLocation: "Unknown original location",
    damaged: "This entry is damaged and cannot be restored. It can only be deleted.",
    sizeBytes: (count: string) => `${count} bytes`,
    quarantinedAt: (when: string) => `quarantined ${when}`,
    unknownTime: "at an unknown time",
    restore: "Restore…",
    delete: "Delete permanently…",
  },
  rules: {
    loadFailed: "Rule status could not be read.",
    unchanged: "The rule pack was not changed.",
    title: "Rule packs",
    active: "Active",
    activeValue: (source: string, sequence: string) => `${source}, sequence ${sequence}`,
    created: "Created",
    contents: "Contents",
    contentsValue: (count: string, description: string) => `${count} rules. ${description}`,
    previous: "Previous pack",
    noneKept: "None kept",
    signatureNote: "Packs are accepted only if their Ed25519 signature matches the key built into this app, and only if they are newer than the active pack. A failed update leaves the active pack in place.",
    testKeyNote: "This build only has a test signing key, so importing and downloading packs is turned off. The built-in pack keeps working.",
    installed: "Rule pack installed.",
    importFromFolder: "Import from folder…",
    downloaded: "Rule pack downloaded and installed.",
    download: "Download latest pack",
    restoredPrevious: "Previous rule pack restored.",
    goBack: "Go back to previous pack…",
    downloadOff: "Downloading is off. Turn it on in Overview if you want it.",
    hiddenTitle: "Hidden heuristic findings",
    hiddenCount: (count: string) => `${count} file contents are hidden from heuristic results. Signed-rule matches are never hidden.`,
    shownAgain: "Hidden findings will show again in the next scan.",
    showAll: "Show all again",
    limitsTitle: "Detection limits",
    limits: "The built-in pack only detects the EICAR test file. Real detection depends on packs you import. YARA rules are not supported.",
  },
  breach: {
    tooLong: (max: string) => `Passwords longer than ${max} bytes can't be checked.`,
    failed: "The check could not be completed. Nothing about the result is known.",
    title: "Password breach check",
    intro: "Checks whether a password appears in the public Pwned Passwords list. Only the first 5 characters of its SHA-1 hash are sent; the match happens on this PC. The password is not stored.",
    emailNote: "E-mail breach monitoring is not offered because it would send your address to a third party.",
    off: "This check is off. Turn on \"Allow the password breach check\" in Overview to use it.",
    password: "Password",
    check: "Check",
    checking: "Checking…",
  },
};

const es419 = {
  layout: {
    eyebrow: "Diagnóstico",
    title: "Protección",
    intro: "Revisa archivos y procesos de esta PC con reglas firmadas y heurísticas locales. Funciona sin conexión y complementa tu antivirus; no lo reemplaza.",
    navLabel: "Secciones de protección",
    sections: {
      overview: "Resumen",
      scan: "Análisis",
      processes: "Procesos",
      quarantine: "Cuarentena",
      rules: "Reglas",
      breach: "Revisión de contraseña",
    },
  },
  evidenceKind: {
    deterministic: "Coincidencia con regla firmada",
    heuristic: "Heurística",
    unavailable: "Sin revisar",
    external: "Respuesta externa",
  },
  evidenceHint: {
    deterministic: "Coincidió con un hash o patrón de bytes de un paquete de reglas firmado.",
    heuristic: "Un patrón local que suele ser sospechoso. Puede ser un falso positivo.",
    unavailable: "No se pudo examinar este elemento. Eso no equivale a que no haya coincidencias.",
    external: "Informado por un componente que esta app no controla.",
  },
  unavailable: {
    accessDenied: "Acceso denegado",
    inUse: "En uso por otro programa",
    tooLarge: "Supera el límite del análisis",
    reparsePoint: "Vínculo o unión, no se siguió",
    notFound: "Ya no existe",
    signerNotCheckable: "No se pudo revisar la firma",
    providerAbsent: "No hay proveedor disponible",
    providerNoResponse: "El proveedor no respondió",
    cancelled: "Cancelado",
    readFailed: "No se pudo leer",
  },
  deterministicDetail: (ruleName: string, ruleId: string, pack: string, exactHash: boolean) =>
    `${ruleName} (regla ${ruleId}, paquete ${pack}, ${exactHash ? "hash exacto" : "patrón de bytes"})`,
  signer: {
    signedBy: (subject: string) => `Firmado: ${subject}`,
    signed: "Firmado",
    unsigned: "Sin firma incrustada",
    invalid: "Firma no válida",
    unavailable: "Firma sin revisar",
    notApplicable: "No es un archivo que se pueda firmar",
  },
  summary: {
    examined: (files: string, pack: string) => `${files} archivos examinados con el paquete de reglas ${pack}`,
    noSignedMatches: "sin coincidencias con reglas firmadas",
    signedMatches: (count: string) => `${count} coincidencias con reglas firmadas`,
    heuristicFindings: (count: string) => `${count} hallazgos heurísticos`,
    notChecked: (count: string) => `${count} elementos sin revisar`,
  },
  rulesSource: {
    installed: "Paquete instalado",
    previousFallback: "Paquete anterior (el paquete más reciente no pasó la verificación)",
    embeddedBaseline: "Paquete base integrado",
  },
  loading: "Cargando…",
  errors: {
    actionFailed: "No se pudo completar la acción.",
  },
  overview: {
    loadFailed: "No se pudo leer el estado de la protección.",
    saveFailed: "No se pudo guardar la configuración.",
    defenderFailed: "No se pudo leer el historial de Defender.",
    loading: "Cargando el estado de la protección…",
    statusTitle: "Estado",
    rules: "Reglas",
    rulesValue: (source: string, sequence: string, count: string) => `${source}: secuencia ${sequence}, ${count} reglas`,
    lastScan: "Último análisis",
    noScan: "Aún no hay análisis",
    quarantine: "Cuarentena",
    quarantineItems: (count: string) => `${count} elementos`,
    networkTitle: "Uso de red",
    networkIntro: "Todo lo siguiente está desactivado de forma predeterminada. El análisis siempre se ejecuta en esta PC sin usar la red.",
    networkLegend: "Funciones opcionales que envían datos",
    ruleDownload: "Permitir descargar paquetes de reglas firmados",
    ruleDownloadHint: "Se conecta a raw.githubusercontent.com solo cuando presionas Descargar. No envía información sobre tus archivos.",
    breachCheck: "Permitir la revisión de contraseñas filtradas",
    breachCheckHint: "Envía solo los primeros 5 caracteres del hash SHA-1 de la contraseña a api.pwnedpasswords.com. La contraseña nunca sale de esta PC.",
    amsi: "Consultar al antivirus instalado sobre archivos marcados (AMSI)",
    amsiHint: "Tu antivirus puede usar su propio servicio en la nube para esto, según su configuración.",
    defenderTitle: "Historial de Microsoft Defender",
    defenderIntro: "Lee lo que Defender ya registró. Esto no inicia un análisis de Defender.",
    readHistory: "Leer el historial de detecciones",
    readingHistory: "Leyendo el historial de Defender…",
    defenderUnavailable: (detail: string) => `${detail}. Es posible que Defender no sea el antivirus activo.`,
    noDetections: "Defender no tiene detecciones registradas.",
    threat: (id: string) => `Amenaza ${id}`,
    unknownThreat: "desconocida",
    firstSeen: (when: string) => `, vista por primera vez ${when}`,
    truncated: "Se muestran las primeras 500 detecciones registradas.",
    heuristicsTitle: "Heurísticas y sus límites",
    falsePositives: (note: string) => `Falsos positivos: ${note}`,
  },
  scan: {
    failed: "No se pudo ejecutar el análisis.",
    quarantined: (path: string) => `Movido a cuarentena: ${path}`,
    allowed: "Los hallazgos heurísticos para este contenido de archivo exacto se ocultarán en análisis futuros.",
    startTitle: "Iniciar un análisis",
    startIntro: "El análisis rápido revisa las carpetas de inicio, Temp, Descargas y los programas en ejecución. El análisis de carpeta revisa una carpeta que elijas. Los vínculos y uniones nunca se siguen.",
    quick: "Análisis rápido",
    folder: "Analizar una carpeta…",
    cancel: "Cancelar análisis",
    scanning: "Analizando…",
    filesExamined: (count: string) => ` ${count} archivos examinados`,
    resultsTitle: "Resultados",
    allowlisted: (count: string) => ` · ${count} ocultos por tu lista de permitidos`,
    reparseSkipped: (count: string) => ` · ${count} vínculos o uniones omitidos (no se siguieron)`,
    cancelled: "Se canceló el análisis; los resultados son parciales.",
    truncated: "El análisis se detuvo en su límite de tamaño; los resultados son parciales.",
    limitsHint: "Un archivo sin hallazgos solo se comparó con las reglas y heurísticas actuales. La detección es limitada; consulta la sección Reglas.",
    falsePositives: (note: string) => `Falsos positivos: ${note}`,
    quarantine: "Poner en cuarentena…",
    hide: "Ocultar para este archivo",
    showingFirst: (shown: string, total: string) => `Se muestran los primeros ${shown} de ${total}.`,
  },
  processes: {
    loadFailed: "No se pudo leer la lista de procesos.",
    title: "Procesos en ejecución",
    intro: "Solo lectura. Esta app nunca finaliza ni modifica procesos; usa el Administrador de tareas para eso. No se leen las líneas de comandos.",
    refresh: "Actualizar",
    filter: "Filtrar",
    loading: "Leyendo procesos…",
    count: (count: string) => `${count} procesos`,
    imageUnavailable: (count: string) => ` · ${count} no se pudieron inspeccionar (normalmente procesos del sistema o de otros usuarios)`,
    truncated: " · lista truncada",
    columns: { name: "Nombre", pid: "PID", parent: "Padre", signature: "Firma", findings: "Hallazgos" },
    none: "Ninguno",
  },
  quarantine: {
    loadFailed: "No se pudo leer la cuarentena.",
    collision: "Ya existe un archivo en la ubicación original, así que no se restauró ni sobrescribió nada. Mueve o cambia el nombre de ese archivo y vuelve a intentarlo.",
    restored: (path: string) => `Restaurado en ${path}`,
    deleted: "Eliminado permanentemente.",
    title: "Cuarentena",
    intro: "Los archivos en cuarentena se guardan de forma codificada para que no puedan ejecutarse. Restaurar nunca sobrescribe un archivo existente. Cada acción pide confirmación en un cuadro de diálogo de Windows.",
    empty: "La cuarentena está vacía.",
    unknownLocation: "Ubicación original desconocida",
    damaged: "Esta entrada está dañada y no se puede restaurar. Solo se puede eliminar.",
    sizeBytes: (count: string) => `${count} bytes`,
    quarantinedAt: (when: string) => `en cuarentena ${when}`,
    unknownTime: "en un momento desconocido",
    restore: "Restaurar…",
    delete: "Eliminar permanentemente…",
  },
  rules: {
    loadFailed: "No se pudo leer el estado de las reglas.",
    unchanged: "El paquete de reglas no se modificó.",
    title: "Paquetes de reglas",
    active: "Activo",
    activeValue: (source: string, sequence: string) => `${source}, secuencia ${sequence}`,
    created: "Creado",
    contents: "Contenido",
    contentsValue: (count: string, description: string) => `${count} reglas. ${description}`,
    previous: "Paquete anterior",
    noneKept: "No se conserva ninguno",
    signatureNote: "Los paquetes solo se aceptan si su firma Ed25519 coincide con la clave integrada en esta app y si son más recientes que el paquete activo. Si una actualización falla, el paquete activo se mantiene.",
    testKeyNote: "Esta compilación solo tiene una clave de firma de prueba, así que importar y descargar paquetes está desactivado. El paquete integrado sigue funcionando.",
    installed: "Paquete de reglas instalado.",
    importFromFolder: "Importar desde una carpeta…",
    downloaded: "Paquete de reglas descargado e instalado.",
    download: "Descargar el paquete más reciente",
    restoredPrevious: "Se restauró el paquete de reglas anterior.",
    goBack: "Volver al paquete anterior…",
    downloadOff: "La descarga está desactivada. Actívala en Resumen si la quieres.",
    hiddenTitle: "Hallazgos heurísticos ocultos",
    hiddenCount: (count: string) => `${count} contenidos de archivo están ocultos de los resultados heurísticos. Las coincidencias con reglas firmadas nunca se ocultan.`,
    shownAgain: "Los hallazgos ocultos volverán a mostrarse en el próximo análisis.",
    showAll: "Mostrar todo de nuevo",
    limitsTitle: "Límites de detección",
    limits: "El paquete integrado solo detecta el archivo de prueba EICAR. La detección real depende de los paquetes que importes. Las reglas YARA no son compatibles.",
  },
  breach: {
    tooLong: (max: string) => `No se pueden revisar contraseñas de más de ${max} bytes.`,
    failed: "No se pudo completar la revisión. No se sabe nada sobre el resultado.",
    title: "Revisión de contraseñas filtradas",
    intro: "Revisa si una contraseña aparece en la lista pública Pwned Passwords. Solo se envían los primeros 5 caracteres de su hash SHA-1; la comparación se hace en esta PC. La contraseña no se guarda.",
    emailNote: "No se ofrece el monitoreo de filtraciones de correo electrónico porque enviaría tu dirección a un tercero.",
    off: "Esta revisión está desactivada. Activa \"Permitir la revisión de contraseñas filtradas\" en Resumen para usarla.",
    password: "Contraseña",
    check: "Revisar",
    checking: "Revisando…",
  },
} satisfies Catalog<typeof en>;

export const protectionStrings = { en, es419 };
export type ProtectionStrings = typeof en;
