import type { Catalog } from "../../shared/i18n/catalog";

const en = {
  title: "Browser caches",
  introScope: "Native cache scopes only. No automatic browser closing or cache cleanup. Cookies, logins, history, bookmarks and site databases are excluded; private profiles are preserved.",
  introRefusal: "Active or unknown browser activity is refused. Close browsers yourself and authorize again to retry. Partial results may omit inaccessible, protected, recent or changing files. Unavailable scopes cannot be authorized; refresh after the browser installation is available.",
  refreshScopes: "Refresh native scopes",
  loading: "Loading native browser policy and scopes...",
  minimumAge: (seconds: string) => `Minimum age: ${seconds} seconds`,
  includeServiceWorker: "Include service-worker caches",
  scopesLegend: "Native browser scopes",
  scopeUnavailable: " (unavailable or unsupported)",
  policySummary: "Native policy and provenance",
  sourceRevision: (source: string, revision: string) => `Source: ${source} | Revision: ${revision}`,
  riskLifecycle: (risk: string, lifecycle: string) => `Risk: ${risk} | Lifecycle: ${lifecycle}`,
  exclusions: (list: string) => `Exclusions: ${list}`,
  profileCacheRoots: (list: string) => `Profile cache roots: ${list}`,
  sharedCacheRoots: (list: string) => `Shared cache roots: ${list}`,
  unsupported: (reason: string) => `Unsupported: ${reason}`,
  cacheLabels: {
    unclassified: "Unclassified cache",
    shared: "Shared cache",
    perProfile: "Per-profile cache",
    perProfileNamed: (profile: string) => `Per-profile cache: ${profile}`,
  },
  authorize: "Authorize selected scope",
  authorizedScope: (path: string) => `Authorized scope: ${path}`,
  scan: "Scan browser scope",
  singleUse: "Authorization is single-use. Authorize again for another scan. Switching scopes releases old authority and results.",
  resultsCaveat: "Results may omit protected, inaccessible, changing or limit-excluded files. Byte totals are not reclaimed space.",
  selected: (count: string, max: string) => `${count} selected (maximum ${max}).`,
  clearSelection: "Clear selection",
  resultsLabel: "Browser results",
  logical: (bytes: string) => `${bytes} logical`,
  unknownAllocation: "Unknown allocation",
  allocated: (bytes: string) => `${bytes} allocated`,
  notSelectable: (reason: string) => `Not selectable: ${reason}`,
  readOnly: "Read-only",
  noMatches: "No matching files on this page.",
  dispositionNote: "App recovery is the default: same-volume storage for manual undo, no space reclaimed and no automatic purge. Permanent deletion is optional and requires Windows confirmation. Windows Recycle Bin is unsupported; there is no path-based fallback.",
};

const es419 = {
  title: "Cachés del navegador",
  introScope: "Solo alcances de caché nativos. No se cierran navegadores ni se limpia la caché automáticamente. Se excluyen cookies, inicios de sesión, historial, marcadores y bases de datos de sitios; los perfiles privados se conservan.",
  introRefusal: "Se rechaza la actividad del navegador activa o desconocida. Cierra los navegadores tú mismo y vuelve a autorizar para reintentar. Los resultados parciales pueden omitir archivos inaccesibles, protegidos, recientes o que están cambiando. Los alcances no disponibles no se pueden autorizar; actualiza cuando la instalación del navegador esté disponible.",
  refreshScopes: "Actualizar alcances nativos",
  loading: "Cargando la política y los alcances nativos del navegador...",
  minimumAge: (seconds: string) => `Antigüedad mínima: ${seconds} segundos`,
  includeServiceWorker: "Incluir cachés de service workers",
  scopesLegend: "Alcances nativos del navegador",
  scopeUnavailable: " (no disponible o no compatible)",
  policySummary: "Política nativa y procedencia",
  sourceRevision: (source: string, revision: string) => `Origen: ${source} | Revisión: ${revision}`,
  riskLifecycle: (risk: string, lifecycle: string) => `Riesgo: ${risk} | Ciclo de vida: ${lifecycle}`,
  exclusions: (list: string) => `Exclusiones: ${list}`,
  profileCacheRoots: (list: string) => `Raíces de caché por perfil: ${list}`,
  sharedCacheRoots: (list: string) => `Raíces de caché compartida: ${list}`,
  unsupported: (reason: string) => `No compatible: ${reason}`,
  cacheLabels: {
    unclassified: "Caché sin clasificar",
    shared: "Caché compartida",
    perProfile: "Caché por perfil",
    perProfileNamed: (profile: string) => `Caché por perfil: ${profile}`,
  },
  authorize: "Autorizar el alcance seleccionado",
  authorizedScope: (path: string) => `Alcance autorizado: ${path}`,
  scan: "Analizar el alcance del navegador",
  singleUse: "La autorización es de un solo uso. Vuelve a autorizar para otro análisis. Cambiar de alcance libera la autorización y los resultados anteriores.",
  resultsCaveat: "Los resultados pueden omitir archivos protegidos, inaccesibles, que están cambiando o excluidos por límites. Los totales de bytes no son espacio recuperado.",
  selected: (count: string, max: string) => `${count} seleccionados (máximo ${max}).`,
  clearSelection: "Borrar selección",
  resultsLabel: "Resultados del navegador",
  logical: (bytes: string) => `${bytes} lógicos`,
  unknownAllocation: "Asignación desconocida",
  allocated: (bytes: string) => `${bytes} asignados`,
  notSelectable: (reason: string) => `No seleccionable: ${reason}`,
  readOnly: "Solo lectura",
  noMatches: "No hay archivos coincidentes en esta página.",
  dispositionNote: "La recuperación de la app es la opción predeterminada: almacenamiento en el mismo volumen para deshacer manualmente, sin recuperar espacio y sin purga automática. La eliminación permanente es opcional y requiere la confirmación de Windows. La Papelera de reciclaje de Windows no es compatible; no hay alternativa basada en rutas.",
} satisfies Catalog<typeof en>;

export const browserStrings = { en, es419 };
export type BrowserStrings = typeof en;
