import type { Catalog } from "../../shared/i18n/catalog";
import type { Weekday } from "../../shared/system-change/types";
import type { OrphanReason } from "./types";

const en = {
  weekday: {
    monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday",
    friday: "Friday", saturday: "Saturday", sunday: "Sunday",
  } satisfies Record<Weekday, string>,
  orphan: {
    foreignExecutable: "The task runs a different program than this installation.",
    malformedArguments: "The task's arguments were changed outside this app.",
    unrecognizedDefinition: "The task's triggers or actions were changed outside this app; it is listed but never modified.",
  } satisfies Record<OrphanReason, string>,
  daily: (time: string) => `Every day at ${time}`,
  weekly: (day: string, time: string) => `Every ${day} at ${time}`,
  loadError: "Scheduled scans could not be read.",
  timeFormat: "Enter a time as HH:MM.",
  describeAdd: (cadence: string) => `Add scheduled scan: ${cadence}`,
  describeRemove: (cadence: string) => `Remove scheduled scan: ${cadence}`,
  eyebrow: "System",
  title: "Scheduled scans",
  intro: "Scheduled scans are read-only: they run a cleanup preview through Windows Task Scheduler and record a summary, and they never delete anything.",
  refresh: "Refresh",
  loading: "Reading scheduled scans…",
  newScheduleLabel: "New scheduled scan",
  frequency: "Frequency",
  dailyOption: "Daily",
  weeklyOption: "Weekly",
  weekdayLabel: "Weekday",
  time: "Time",
  addSchedule: "Add schedule",
  pendingTitle: "New schedules to review",
  discardLabel: (cadence: string) => `Discard new schedule: ${cadence}`,
  discard: "Discard",
  existingTitle: "Existing schedules",
  noSchedules: "No scheduled scans.",
  unrecognized: "Unrecognized schedule",
  enabled: "Enabled",
  disabled: "Disabled in Task Scheduler",
  lastRun: (value: string) => ` · Last run: ${value}`,
  nextRun: (value: string) => ` · Next run: ${value}`,
  never: "Never",
  notScheduled: "Not scheduled",
  orphaned: (reason: string) => `Orphaned: ${reason}`,
  orphanedFallback: "The task no longer matches this app.",
  cannotRemove: "This task cannot be removed here because its definition is not recognized.",
  removeSchedule: "Remove schedule",
  recentTitle: "Recent scheduled scan results",
  noRecent: "No scheduled scan has finished yet.",
  unknownTime: "Unknown time",
  summary: (bytes: string, items: string, diagnostics: string) => `${bytes} reclaimable in ${items} items, ${diagnostics} diagnostics`,
  didNotFinish: "Scan did not finish",
};

const es419 = {
  weekday: {
    monday: "lunes", tuesday: "martes", wednesday: "miércoles", thursday: "jueves",
    friday: "viernes", saturday: "sábado", sunday: "domingo",
  },
  orphan: {
    foreignExecutable: "La tarea ejecuta un programa distinto al de esta instalación.",
    malformedArguments: "Los argumentos de la tarea se cambiaron fuera de esta app.",
    unrecognizedDefinition: "Los desencadenadores o las acciones de la tarea se cambiaron fuera de esta app; aparece en la lista pero nunca se modifica.",
  },
  daily: (time: string) => `Todos los días a las ${time}`,
  weekly: (day: string, time: string) => `Cada ${day} a las ${time}`,
  loadError: "No se pudieron leer los análisis programados.",
  timeFormat: "Escribe una hora con el formato HH:MM.",
  describeAdd: (cadence: string) => `Agregar análisis programado: ${cadence}`,
  describeRemove: (cadence: string) => `Quitar análisis programado: ${cadence}`,
  eyebrow: "Sistema",
  title: "Análisis programados",
  intro: "Los análisis programados son de solo lectura: ejecutan una vista previa de la limpieza mediante el Programador de tareas de Windows y registran un resumen, y nunca eliminan nada.",
  refresh: "Actualizar",
  loading: "Leyendo los análisis programados…",
  newScheduleLabel: "Nuevo análisis programado",
  frequency: "Frecuencia",
  dailyOption: "Diario",
  weeklyOption: "Semanal",
  weekdayLabel: "Día de la semana",
  time: "Hora",
  addSchedule: "Agregar programación",
  pendingTitle: "Nuevas programaciones para revisar",
  discardLabel: (cadence: string) => `Descartar la nueva programación: ${cadence}`,
  discard: "Descartar",
  existingTitle: "Programaciones existentes",
  noSchedules: "No hay análisis programados.",
  unrecognized: "Programación no reconocida",
  enabled: "Habilitada",
  disabled: "Deshabilitada en el Programador de tareas",
  lastRun: (value: string) => ` · Última ejecución: ${value}`,
  nextRun: (value: string) => ` · Próxima ejecución: ${value}`,
  never: "Nunca",
  notScheduled: "Sin programar",
  orphaned: (reason: string) => `Huérfana: ${reason}`,
  orphanedFallback: "La tarea ya no coincide con esta app.",
  cannotRemove: "Esta tarea no se puede quitar aquí porque no se reconoce su definición.",
  removeSchedule: "Quitar programación",
  recentTitle: "Resultados recientes de análisis programados",
  noRecent: "Todavía no terminó ningún análisis programado.",
  unknownTime: "Hora desconocida",
  summary: (bytes: string, items: string, diagnostics: string) => `${bytes} recuperables en ${items} elementos, ${diagnostics} diagnósticos`,
  didNotFinish: "El análisis no terminó",
} satisfies Catalog<typeof en>;

export const schedulerStrings = { en, es419 };
export type SchedulerStrings = typeof en;
