import type { CleanupDisposition, CleanupItemState } from "../cleanup/api";
import type { Catalog } from "../i18n/catalog";
import type { ScanPhase } from "./types";

const en = {
  errors: {
    busy: "Another scan is active. Cancel it or wait before starting again.",
    snapshot_unavailable: "These results expired or were released. Start a new scan.",
    scope_unavailable: "This scope is unavailable. Choose another supported scope.",
    invalid_cursor: "This page is no longer available. Return to the first page or scan again.",
    limit_reached: "The safety limit was reached. Narrow the scope or select fewer items.",
    recovery_volume_unsupported: "App recovery is unavailable for the selected volume. No recovery plan was created.",
    invalid_evidence: "The selection no longer matches the scan. Scan again before reviewing.",
    fallback: "Storage could not continue. Start a new scan before retrying.",
  },
  scan: {
    phases: {
      idle: "Choose a scope, then start a scan.",
      starting: "Starting scan…",
      scanning: "Scanning. No files are being changed.",
      ready: "Scan complete.",
      cancelling: "Requesting cancellation…",
      cancelled: "Scan cancelled. Results and selections were discarded. Start a new scan to continue.",
      failed: "Scan unavailable. Start a new scan to continue.",
    } satisfies Record<ScanPhase, string>,
    partial: "Results are partial; totals may be incomplete.",
    statusLabel: "Storage scan status",
    progress: (entries: string, records: string) => `${entries} entries checked · ${records} records retained`,
    hashing: (bytes: string, hashes: string) => `${bytes} hashed · ${hashes} hashes completed`,
    cancelScan: "Cancel scan",
    cancellationUnconfirmed: "Cancellation could not be confirmed. Results were discarded; wait before starting again.",
    pagesLabel: "Scan result pages",
    loadingPage: "Loading page…",
    pageSummary: (count: string, total: string) => `${count} records on this page; ${total} retained in this view.`,
    firstPage: "First page",
    nextPage: "Next page",
  },
  outcomes: {
    states: {
      pending: "Not confirmed", mutating: "Not confirmed", unknown: "Uncertain",
      recycled: "Retained in Recycle Bin", quarantined: "Retained in app recovery",
      purged: "Permanently removed", restored: "Restored", failed: "Failed",
    } satisfies Record<CleanupItemState, string>,
    failures: {
      identityUnproven: "Recovery identity could not be verified. The location and safety of this item are uncertain. Preserve recovery data and seek help; do not retry or move recovery files.",
      uncertain: "The result is not confirmed. Do not assume this item was deleted or is safely recoverable. Preserve history and inspect before further action.",
      notFound: "The item was already gone when cleanup reached it. Nothing was removed.",
      inUse: "The item is open in another program, so it was left untouched. Close that program and scan again.",
      permissionDenied: "Windows denied access to the item, so it was left untouched.",
      permanentRemoveFailed: "Removal was refused. The item may have changed or the folder may no longer be empty. Inspect it and scan again before any new cleanup.",
      restoreProtectionRejected: "Restoration was blocked by current protection or browser activity checks. Keep recovery data intact; do not bypass protection.",
      restoreRejected: "Restoration was refused because the destination or recovery checks did not pass. Inspect the original location; do not overwrite it or move recovery files.",
      restoreFailed: "Restoration could not be confirmed. Preserve recovery data and inspect the original location before further action.",
      generic: "The operation did not succeed. Inspect the item and preserve recovery data. No automatic retry will run.",
    },
    totalItems: (n: number) => `${n} total items`,
    failedItems: (n: number) => `${n} failed item${n === 1 ? "" : "s"}`,
    uncertainItems: (n: number) => `${n} uncertain item${n === 1 ? "" : "s"}`,
    confirmedItems: (n: number) => `${n} confirmed item${n === 1 ? "" : "s"}`,
    itemOutcomes: "Item outcomes",
    accounting: (reclaimed: string, failed: string, occupied: string) => `${reclaimed} reclaimed · ${failed} failed · ${occupied} still occupied`,
    breakdown: (processed: string, quarantined: string, purged: string) => `Processed: ${processed}. Quarantined: ${quarantined}. Purged: ${purged}.`,
    range: (from: number, to: number, total: number) => `Items ${from}–${to} of ${total}`,
    displayUnavailable: "Display location unavailable",
    itemId: (id: string) => `Item ID: ${id}`,
    uncertain: "Uncertain",
    logicalSize: (bytes: string) => `${bytes} logical size`,
    operationFailed: "Operation failed",
    previousItems: "Previous items",
    nextItems: "Next items",
  },
  review: {
    dispositions: {
      recycleBin: "Move to Recycle Bin", quarantine: "Move to app recovery", permanent: "Delete permanently",
    } satisfies Record<CleanupDisposition, string>,
    regionLabel: "Storage cleanup review",
    reviewAction: (label: string) => `Review: ${label}`,
    refreshHistory: "Refresh newest cleanup history",
    loadHistory: "Load cleanup history",
    waiting: "Waiting for the native operation…",
    operationUnconfirmed: "The operation was not confirmed or could not finish. Load history to check outcomes before retrying.",
    permanentSeparate: "Permanent deletion remains a separate choice: select Review: Delete permanently, then confirm in Windows. It cannot be undone.",
    reviewCleanup: "Review cleanup",
    planSummary: (count: number | undefined, bytes: string) => `${count ?? ""} ${count === 1 ? "item" : "items"} · ${bytes} selected, not reclaimed.`,
    planFixed: "This plan is fixed to the reviewed scan and selection. Changed files can be refused at execution.",
    permanentWarning: "This cannot be undone. Continuing opens a separate Windows confirmation.",
    quarantineNote: "Files are held in app recovery storage on the same volume, without automatic purge. This does not free disk space.",
    recycleNote: "Files go to the Windows Recycle Bin where supported.",
    undoNote: "Undo is available only for items successfully retained for recovery.",
    cancelReview: "Cancel review",
    continueToWindows: "Continue to Windows confirmation",
    confirm: "Confirm",
    latestOutcomeLabel: "Latest storage cleanup outcome",
    finished: "Cleanup finished",
    needsAttention: "Cleanup needs attention",
    historyLabel: "Storage cleanup history",
    recentHistory: "Recent cleanup history",
    historyRow: (label: string, bytes: string) => `${label} · ${bytes} reclaimed`,
    rowNeedsAttention: "Needs attention",
    undoCleanup: "Undo cleanup",
    historyPaging: "Up to 20 executions per page. Undo can fail if retained files have changed.",
    loadingHistory: "Loading cleanup history…",
    historyNotLoaded: "Cleanup history has not been loaded.",
    noHistory: "No cleanup history yet.",
    endOfHistory: "End of cleanup history.",
    olderHistory: "Older cleanup history",
  },
};

const es419 = {
  errors: {
    busy: "Hay otro análisis en curso. Cancélalo o espera antes de empezar de nuevo.",
    snapshot_unavailable: "Estos resultados vencieron o se liberaron. Inicia un nuevo análisis.",
    scope_unavailable: "Este alcance no está disponible. Elige otro alcance compatible.",
    invalid_cursor: "Esta página ya no está disponible. Vuelve a la primera página o analiza de nuevo.",
    limit_reached: "Se alcanzó el límite de seguridad. Reduce el alcance o selecciona menos elementos.",
    recovery_volume_unsupported: "La recuperación de la app no está disponible para el volumen seleccionado. No se creó ningún plan de recuperación.",
    invalid_evidence: "La selección ya no coincide con el análisis. Analiza de nuevo antes de revisar.",
    fallback: "El almacenamiento no pudo continuar. Inicia un nuevo análisis antes de reintentar.",
  },
  scan: {
    phases: {
      idle: "Elige un alcance y luego inicia un análisis.",
      starting: "Iniciando análisis…",
      scanning: "Analizando. No se está modificando ningún archivo.",
      ready: "Análisis completo.",
      cancelling: "Solicitando la cancelación…",
      cancelled: "Análisis cancelado. Se descartaron los resultados y las selecciones. Inicia un nuevo análisis para continuar.",
      failed: "Análisis no disponible. Inicia un nuevo análisis para continuar.",
    },
    partial: "Los resultados son parciales; los totales pueden estar incompletos.",
    statusLabel: "Estado del análisis de almacenamiento",
    progress: (entries: string, records: string) => `${entries} entradas revisadas · ${records} registros conservados`,
    hashing: (bytes: string, hashes: string) => `${bytes} con hash calculado · ${hashes} hashes completados`,
    cancelScan: "Cancelar análisis",
    cancellationUnconfirmed: "No se pudo confirmar la cancelación. Se descartaron los resultados; espera antes de empezar de nuevo.",
    pagesLabel: "Páginas de resultados del análisis",
    loadingPage: "Cargando página…",
    pageSummary: (count: string, total: string) => `${count} registros en esta página; ${total} conservados en esta vista.`,
    firstPage: "Primera página",
    nextPage: "Página siguiente",
  },
  outcomes: {
    states: {
      pending: "Sin confirmar", mutating: "Sin confirmar", unknown: "Incierto",
      recycled: "Conservado en la Papelera de reciclaje", quarantined: "Conservado en la recuperación de la app",
      purged: "Eliminado permanentemente", restored: "Restaurado", failed: "Falló",
    },
    failures: {
      identityUnproven: "No se pudo verificar la identidad de recuperación. La ubicación y la seguridad de este elemento son inciertas. Conserva los datos de recuperación y busca ayuda; no reintentes ni muevas los archivos de recuperación.",
      uncertain: "El resultado no está confirmado. No supongas que este elemento se eliminó o que se puede recuperar de forma segura. Conserva el historial e inspecciona antes de hacer algo más.",
      notFound: "El elemento ya no existía cuando la limpieza llegó a él. No se eliminó nada.",
      inUse: "El elemento está abierto en otro programa, así que no se tocó. Cierra ese programa y analiza de nuevo.",
      permissionDenied: "Windows denegó el acceso al elemento, así que no se tocó.",
      permanentRemoveFailed: "Se rechazó la eliminación. Es posible que el elemento haya cambiado o que la carpeta ya no esté vacía. Inspecciónalo y analiza de nuevo antes de cualquier nueva limpieza.",
      restoreProtectionRejected: "La restauración fue bloqueada por las comprobaciones actuales de protección o de actividad del navegador. Mantén intactos los datos de recuperación; no omitas la protección.",
      restoreRejected: "Se rechazó la restauración porque no se superaron las comprobaciones del destino o de recuperación. Inspecciona la ubicación original; no la sobrescribas ni muevas los archivos de recuperación.",
      restoreFailed: "No se pudo confirmar la restauración. Conserva los datos de recuperación e inspecciona la ubicación original antes de hacer algo más.",
      generic: "La operación no tuvo éxito. Inspecciona el elemento y conserva los datos de recuperación. No se hará ningún reintento automático.",
    },
    totalItems: (n: number) => `${n} elementos en total`,
    failedItems: (n: number) => `${n} ${n === 1 ? "elemento fallido" : "elementos fallidos"}`,
    uncertainItems: (n: number) => `${n} ${n === 1 ? "elemento incierto" : "elementos inciertos"}`,
    confirmedItems: (n: number) => `${n} ${n === 1 ? "elemento confirmado" : "elementos confirmados"}`,
    itemOutcomes: "Resultados por elemento",
    accounting: (reclaimed: string, failed: string, occupied: string) => `${reclaimed} recuperados · ${failed} con error · ${occupied} aún ocupados`,
    breakdown: (processed: string, quarantined: string, purged: string) => `Procesado: ${processed}. En recuperación de la app: ${quarantined}. Purgado: ${purged}.`,
    range: (from: number, to: number, total: number) => `Elementos ${from}–${to} de ${total}`,
    displayUnavailable: "Ubicación para mostrar no disponible",
    itemId: (id: string) => `ID del elemento: ${id}`,
    uncertain: "Incierto",
    logicalSize: (bytes: string) => `${bytes} de tamaño lógico`,
    operationFailed: "La operación falló",
    previousItems: "Elementos anteriores",
    nextItems: "Elementos siguientes",
  },
  review: {
    dispositions: {
      recycleBin: "Mover a la Papelera de reciclaje", quarantine: "Mover a la recuperación de la app", permanent: "Eliminar permanentemente",
    },
    regionLabel: "Revisión de la limpieza de almacenamiento",
    reviewAction: (label: string) => `Revisar: ${label}`,
    refreshHistory: "Actualizar el historial de limpieza más reciente",
    loadHistory: "Cargar historial de limpieza",
    waiting: "Esperando la operación nativa…",
    operationUnconfirmed: "La operación no se confirmó o no pudo terminar. Carga el historial para revisar los resultados antes de reintentar.",
    permanentSeparate: "La eliminación permanente sigue siendo una opción aparte: selecciona Revisar: Eliminar permanentemente y luego confirma en Windows. No se puede deshacer.",
    reviewCleanup: "Revisar limpieza",
    planSummary: (count: number | undefined, bytes: string) => `${count ?? ""} ${count === 1 ? "elemento" : "elementos"} · ${bytes} seleccionados, no recuperados.`,
    planFixed: "Este plan está fijado al análisis y la selección revisados. Los archivos que cambiaron pueden rechazarse al ejecutarlo.",
    permanentWarning: "Esto no se puede deshacer. Al continuar se abre una confirmación de Windows aparte.",
    quarantineNote: "Los archivos se guardan en el almacenamiento de recuperación de la app en el mismo volumen, sin purga automática. Esto no libera espacio en disco.",
    recycleNote: "Los archivos van a la Papelera de reciclaje de Windows cuando es compatible.",
    undoNote: "Deshacer solo está disponible para los elementos que se conservaron correctamente para recuperación.",
    cancelReview: "Cancelar revisión",
    continueToWindows: "Continuar a la confirmación de Windows",
    confirm: "Confirmar",
    latestOutcomeLabel: "Resultado más reciente de la limpieza de almacenamiento",
    finished: "Limpieza terminada",
    needsAttention: "La limpieza requiere atención",
    historyLabel: "Historial de limpieza de almacenamiento",
    recentHistory: "Historial de limpieza reciente",
    historyRow: (label: string, bytes: string) => `${label} · ${bytes} recuperados`,
    rowNeedsAttention: "Requiere atención",
    undoCleanup: "Deshacer limpieza",
    historyPaging: "Hasta 20 ejecuciones por página. Deshacer puede fallar si los archivos conservados cambiaron.",
    loadingHistory: "Cargando historial de limpieza…",
    historyNotLoaded: "El historial de limpieza no se ha cargado.",
    noHistory: "Todavía no hay historial de limpieza.",
    endOfHistory: "Fin del historial de limpieza.",
    olderHistory: "Historial de limpieza anterior",
  },
} satisfies Catalog<typeof en>;

export const storageStrings = { en, es419 };
export type StorageStrings = typeof en;
