import type { Catalog } from "../../shared/i18n/catalog";
import type { ArtifactIntelligence, ArtifactType } from "./api/previewCleanup";

type RebuildConsequence = ArtifactIntelligence["rebuildConsequence"];

const en = {
  documentTitle: "Cleanup | Supa Diska Klinah",
  kicker: "Temporary files",
  heading: "Cleanup",
  intro: "Review every item first. Cleanup uses the Windows Recycle Bin by default.",
  scanning: "Scanning…",
  tryAgain: "Try again",
  scanAgain: "Scan again",
  loadingTitle: "Scanning temporary caches",
  loadingBody: "Checking fixed Windows locations without changing files.",
  errorTitle: "Cleanup could not continue",
  errorBody: "Nothing else was changed. Scan again before retrying.",
  emptyTitle: "Nothing found",
  emptyBody: "No cache or tmp directories are currently eligible.",
  skippedLocations: (count: number) => `${count} skipped ${count === 1 ? "location" : "locations"}`,
  selectedOf: (selected: number, total: number) => `${selected} of ${total} selected`,
  bytesSelected: (bytes: string) => `${bytes} selected`,
  recordPagesLabel: "Cleanup result pages",
  recordRange: (from: number, to: number, total: number) => `Showing ${from}–${to} of ${total}`,
  previousRecords: "Previous results",
  nextRecords: "Next results",
  clearSelection: "Clear selection",
  selectAll: "Select all",
  directory: "Directory",
  file: "File",
  modified: (when: string) => ` · Modified ${when}`,
  moveToRecycleBin: "Move to Recycle Bin",
  deletePermanently: "Delete permanently",
  confirmPermanentTitle: "Permanently delete these items?",
  confirmRecycleTitle: "Move these items to the Recycle Bin?",
  itemCount: (count: number) => `${count} ${count === 1 ? "item" : "items"}`,
  permanentWarning: "This cannot be undone by Supa Diska Klinah.",
  cancel: "Cancel",
  working: "Working…",
  latestCleanup: "Latest cleanup",
  undoCleanup: "Undo cleanup",
  accounting: {
    selected: "Selected",
    processed: "Processed",
    failed: "Failed",
    quarantined: "Quarantined",
    purged: "Purged",
    occupied: "Occupied",
    reclaimed: "Reclaimed",
  },
  history: {
    title: "Cleanup history",
    refresh: "Refresh newest cleanup history",
    older: "Older cleanup history",
    pageSize: "Up to 20 executions per page.",
    loading: "Loading cleanup history…",
    notLoaded: "Cleanup history has not been loaded.",
    empty: "No cleanup history yet.",
    end: "End of cleanup history.",
    reclaimed: (bytes: string) => `${bytes} reclaimed`,
    undo: "Undo historical cleanup",
  },
  projects: {
    kicker: "Developer storage",
    heading: "Coding project artifacts",
    help: "Save explicit project roots, then scan marker-backed rebuildable files. Nothing is selected or removed.",
    rootTooLong: (maxBytes: string) => `Project root must be ${maxBytes} UTF-8 bytes or fewer.`,
    addLabel: "Add an absolute project path",
    adding: "Adding…",
    addRoot: "Add root",
    reloadRoots: "Reload saved roots",
    savedRoots: "Saved roots",
    scanning: "Scanning…",
    scanActive: "Scan active roots",
    loadingRoots: "Loading saved roots.",
    noRoots: "No roots saved. Add one absolute path to begin.",
    paused: "Paused",
    active: "Active",
    lastScan: "Last scan: ",
    never: "Never",
    scan: "Scan",
    scanRoot: (path: string) => `Scan ${path}`,
    pause: "Pause",
    resume: "Resume",
    pauseRoot: (path: string) => `Pause ${path}`,
    resumeRoot: (path: string) => `Resume ${path}`,
    remove: "Remove",
    removeRoot: (path: string) => `Remove ${path}`,
    removeNote: "Removing a root only forgets it. Project files stay unchanged.",
    idle: "Choose Scan when you want to inspect saved roots.",
    scanningRoots: "Scanning project roots without changing files.",
    noArtifacts: "No marker-backed project artifacts were found.",
    found: (count: number) =>
      `${count} rebuildable ${count === 1 ? "artifact" : "artifacts"} found. All are not selected.`,
    diagnostics: (count: number) =>
      `${count} ${count === 1 ? "location was" : "locations were"} skipped or suppressed to avoid overlap.`,
    listLabel: "Discovered project artifacts",
    size: "Size",
    age: "Age",
    modified: "Modified",
    unavailable: "Unavailable",
    activity: "Activity",
    inUse: "In use",
    idleActivity: "Idle",
    confidence: "Confidence",
    high: "High",
    medium: "Medium",
    risk: "Risk",
    safe: "Safe",
    highImpact: "High impact",
    recoverable: "Recoverable",
    recoverability: "Recoverability",
    rebuildable: "Rebuildable",
    rebuildConsequence: "Rebuild consequence",
    selection: "Selection",
    notSelected: "Not selected",
    ageSeconds: (n: number) => `${n} seconds`,
    ageMinutes: (n: number) => `${n} ${n === 1 ? "minute" : "minutes"}`,
    ageHours: (n: number) => `${n} ${n === 1 ? "hour" : "hours"}`,
    ageDays: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
    artifacts: {
      installedDependencies: "Installed dependencies",
      buildOutput: "Build output",
      compilerCache: "Compiler cache",
      frameworkCache: "Framework cache",
      virtualEnvironment: "Virtual environment",
      testCache: "Test cache",
      generatedIntermediate: "Generated intermediate",
      importedAssetCache: "Imported asset cache",
    } satisfies Record<ArtifactType, string>,
    consequences: {
      localRebuild: "Local rebuild",
      networkDownloadRequired: "Network download required",
      toolchainRequired: "Toolchain required",
      expensiveReimport: "Expensive asset reimport",
    } satisfies Record<RebuildConsequence, string>,
    errors: {
      duplicateRoot: "That project root is already saved.",
      invalidInput: "Enter an existing, unprotected absolute project path.",
      notFound: "That saved project root is no longer available.",
      rootLimitReached: "Remove a project root before adding another.",
      rootPaused: "Resume this project root before scanning it.",
      persistenceFailed: "Saved project roots could not be updated.",
      fallback: "Project roots could not be updated. Try again.",
    },
  },
};

const es419 = {
  documentTitle: "Limpieza | Supa Diska Klinah",
  kicker: "Archivos temporales",
  heading: "Limpieza",
  intro: "Revisa cada elemento primero. La limpieza usa la Papelera de reciclaje de Windows de forma predeterminada.",
  scanning: "Analizando…",
  tryAgain: "Intentar de nuevo",
  scanAgain: "Analizar de nuevo",
  loadingTitle: "Analizando cachés temporales",
  loadingBody: "Revisando ubicaciones fijas de Windows sin cambiar archivos.",
  errorTitle: "La limpieza no pudo continuar",
  errorBody: "No se cambió nada más. Analiza de nuevo antes de reintentar.",
  emptyTitle: "No se encontró nada",
  emptyBody: "Ningún directorio de caché o tmp es apto en este momento.",
  skippedLocations: (count: number) => `${count} ${count === 1 ? "ubicación omitida" : "ubicaciones omitidas"}`,
  selectedOf: (selected: number, total: number) =>
    `${selected} de ${total} ${selected === 1 ? "seleccionado" : "seleccionados"}`,
  bytesSelected: (bytes: string) => `${bytes} seleccionados`,
  recordPagesLabel: "Páginas de resultados de limpieza",
  recordRange: (from: number, to: number, total: number) => `Mostrando ${from}–${to} de ${total}`,
  previousRecords: "Resultados anteriores",
  nextRecords: "Resultados siguientes",
  clearSelection: "Borrar selección",
  selectAll: "Seleccionar todo",
  directory: "Directorio",
  file: "Archivo",
  modified: (when: string) => ` · Modificado ${when}`,
  moveToRecycleBin: "Mover a la Papelera de reciclaje",
  deletePermanently: "Eliminar permanentemente",
  confirmPermanentTitle: "¿Eliminar permanentemente estos elementos?",
  confirmRecycleTitle: "¿Mover estos elementos a la Papelera de reciclaje?",
  itemCount: (count: number) => `${count} ${count === 1 ? "elemento" : "elementos"}`,
  permanentWarning: "Supa Diska Klinah no puede deshacer esta acción.",
  cancel: "Cancelar",
  working: "Procesando…",
  latestCleanup: "Última limpieza",
  undoCleanup: "Deshacer limpieza",
  accounting: {
    selected: "Seleccionado",
    processed: "Procesado",
    failed: "Con error",
    quarantined: "En recuperación de la app",
    purged: "Purgado",
    occupied: "Ocupado",
    reclaimed: "Recuperado",
  },
  history: {
    title: "Historial de limpieza",
    refresh: "Actualizar historial de limpieza más reciente",
    older: "Historial de limpieza anterior",
    pageSize: "Hasta 20 ejecuciones por página.",
    loading: "Cargando historial de limpieza…",
    notLoaded: "El historial de limpieza no se ha cargado.",
    empty: "Todavía no hay historial de limpieza.",
    end: "Fin del historial de limpieza.",
    reclaimed: (bytes: string) => `${bytes} recuperados`,
    undo: "Deshacer limpieza del historial",
  },
  projects: {
    kicker: "Almacenamiento de desarrollo",
    heading: "Artefactos de proyectos de programación",
    help: "Guarda raíces de proyecto explícitas y luego analiza archivos reconstruibles respaldados por marcadores. No se selecciona ni se elimina nada.",
    rootTooLong: (maxBytes: string) => `La raíz del proyecto debe tener ${maxBytes} bytes UTF-8 o menos.`,
    addLabel: "Agrega una ruta absoluta de proyecto",
    adding: "Agregando…",
    addRoot: "Agregar raíz",
    reloadRoots: "Volver a cargar raíces guardadas",
    savedRoots: "Raíces guardadas",
    scanning: "Analizando…",
    scanActive: "Analizar raíces activas",
    loadingRoots: "Cargando raíces guardadas.",
    noRoots: "No hay raíces guardadas. Agrega una ruta absoluta para comenzar.",
    paused: "En pausa",
    active: "Activa",
    lastScan: "Último análisis: ",
    never: "Nunca",
    scan: "Analizar",
    scanRoot: (path: string) => `Analizar ${path}`,
    pause: "Pausar",
    resume: "Reanudar",
    pauseRoot: (path: string) => `Pausar ${path}`,
    resumeRoot: (path: string) => `Reanudar ${path}`,
    remove: "Quitar",
    removeRoot: (path: string) => `Quitar ${path}`,
    removeNote: "Quitar una raíz solo hace que se olvide. Los archivos del proyecto no cambian.",
    idle: "Elige Analizar cuando quieras inspeccionar las raíces guardadas.",
    scanningRoots: "Analizando raíces de proyecto sin cambiar archivos.",
    noArtifacts: "No se encontraron artefactos de proyecto respaldados por marcadores.",
    found: (count: number) =>
      count === 1
        ? `Se encontró ${count} artefacto reconstruible. Ninguno está seleccionado.`
        : `Se encontraron ${count} artefactos reconstruibles. Ninguno está seleccionado.`,
    diagnostics: (count: number) =>
      count === 1
        ? `Se omitió o suprimió ${count} ubicación para evitar superposiciones.`
        : `Se omitieron o suprimieron ${count} ubicaciones para evitar superposiciones.`,
    listLabel: "Artefactos de proyecto encontrados",
    size: "Tamaño",
    age: "Antigüedad",
    modified: "Modificado",
    unavailable: "No disponible",
    activity: "Actividad",
    inUse: "En uso",
    idleActivity: "Inactivo",
    confidence: "Confianza",
    high: "Alta",
    medium: "Media",
    risk: "Riesgo",
    safe: "Seguro",
    highImpact: "Alto impacto",
    recoverable: "Recuperable",
    recoverability: "Recuperabilidad",
    rebuildable: "Reconstruible",
    rebuildConsequence: "Consecuencia de reconstrucción",
    selection: "Selección",
    notSelected: "No seleccionado",
    ageSeconds: (n: number) => `${n} ${n === 1 ? "segundo" : "segundos"}`,
    ageMinutes: (n: number) => `${n} ${n === 1 ? "minuto" : "minutos"}`,
    ageHours: (n: number) => `${n} ${n === 1 ? "hora" : "horas"}`,
    ageDays: (n: number) => `${n} ${n === 1 ? "día" : "días"}`,
    artifacts: {
      installedDependencies: "Dependencias instaladas",
      buildOutput: "Salida de compilación",
      compilerCache: "Caché del compilador",
      frameworkCache: "Caché del framework",
      virtualEnvironment: "Entorno virtual",
      testCache: "Caché de pruebas",
      generatedIntermediate: "Intermedio generado",
      importedAssetCache: "Caché de recursos importados",
    },
    consequences: {
      localRebuild: "Reconstrucción local",
      networkDownloadRequired: "Requiere descarga de red",
      toolchainRequired: "Requiere cadena de herramientas",
      expensiveReimport: "Reimportación de recursos costosa",
    },
    errors: {
      duplicateRoot: "Esa raíz de proyecto ya está guardada.",
      invalidInput: "Ingresa una ruta absoluta de proyecto existente y no protegida.",
      notFound: "Esa raíz de proyecto guardada ya no está disponible.",
      rootLimitReached: "Quita una raíz de proyecto antes de agregar otra.",
      rootPaused: "Reanuda esta raíz de proyecto antes de analizarla.",
      persistenceFailed: "No se pudieron actualizar las raíces de proyecto guardadas.",
      fallback: "No se pudieron actualizar las raíces de proyecto. Intenta de nuevo.",
    },
  },
} satisfies Catalog<typeof en>;

export const cleanupStrings = { en, es419 };
export type CleanupStrings = typeof en;
export type ProjectRootErrorKey = keyof CleanupStrings["projects"]["errors"];
