import type { Catalog } from "../i18n/catalog";
import type { RestartRequirement, RiskLevel, RollbackStatus, UnsupportedReason } from "./types";

const en = {
  risk: { low: "Low risk", medium: "Medium risk", high: "High risk" } satisfies Record<RiskLevel, string>,
  restart: { none: "", signOut: "Sign-out required", reboot: "Restart required" } satisfies Record<RestartRequirement, string>,
  unsupported: {
    apiUnavailable: "Windows does not provide this feature here",
    osVersion: "Not supported on this Windows version",
    editionUnsupported: "Not honored by this Windows edition",
    managedDevice: "Managed by your organization",
    notPresent: "Not present on this device",
  } satisfies Record<UnsupportedReason, string>,
  notSupportedOnDevice: "Not supported on this device",
  reversible: "Can be undone",
  reversibleWithBackup: "Can be undone from a backup",
  irreversible: (reason: string) => `Cannot be undone: ${reason}`,
  outcomeInterrupted: "Interrupted before finishing; state unknown",
  outcomeApplied: "Applied",
  outcomeAlreadyApplied: "Already in place; nothing changed",
  outcomeStateChanged: "Skipped: the setting changed since review",
  outcomeDenied: "Denied: administrator permission was not granted",
  outcomeUnsupported: (reason: string) => `Skipped: ${reason}`,
  outcomeNotAttempted: "Not attempted",
  outcomeFailed: "Failed",
  needsAdministrator: "Needs administrator",
  rollback: {
    available: "Can be undone",
    alreadyRolledBack: "Already undone",
    irreversible: "Cannot be undone",
    interrupted: "Interrupted; check the setting manually",
    nothingApplied: "Nothing to undo",
  } satisfies Record<RollbackStatus, string>,
  resultsLabel: "System change results",
  allFinished: "All changes finished.",
  someUnfinished: "Some changes did not finish. Each result below says what happened; nothing else was changed silently.",
  reviewAndApply: "Review and apply",
  reviewSelected: "Review selected changes",
  reviewButton: (label: string, count: number) => `${label} (${count})`,
  tooMany: (max: number) => `Select at most ${max} changes at a time.`,
  checkingState: "Checking the current state of each change…",
  ticketIntro: (requiresHelper: boolean, seconds: number) =>
    `These changes will be made in order. Windows will ask you to confirm; ${requiresHelper ? "administrator permission (UAC) will be requested once." : "no administrator permission is needed."} This review expires in ${seconds} seconds.`,
  continueToWindows: "Continue to Windows confirmation",
  discardReview: "Discard review",
  applying: "Waiting for Windows confirmation and applying…",
  historyTitle: "Change history",
  historyEmpty: "No changes recorded yet.",
  reviewUndo: (count: number) => `Review undo (${count})`,
  undoIntro: "Undo restores the state recorded before each change. Windows will ask you to confirm.",
  errors: {
    confirmationDeclined: "You cancelled the Windows confirmation. Nothing was changed.",
    planExpired: "The review expired after 60 seconds. Review the changes again.",
    planNotFound: "This review is no longer valid. Review the changes again.",
    unsupported: "This change is not supported on this device.",
    busy: "Another system change is still running.",
    tooManyChanges: "Select at most 32 changes at a time.",
    journalUnavailable:
      "The change history could not be read. It may have been written by a newer version of this app; update the app, or see the administrator guide to reset it.",
    fallback: "The system change could not be completed.",
  },
};

const es419 = {
  risk: { low: "Riesgo bajo", medium: "Riesgo medio", high: "Riesgo alto" },
  restart: { none: "", signOut: "Requiere cerrar sesión", reboot: "Requiere reiniciar" },
  unsupported: {
    apiUnavailable: "Windows no ofrece esta función aquí",
    osVersion: "No es compatible con esta versión de Windows",
    editionUnsupported: "Esta edición de Windows no la aplica",
    managedDevice: "Administrado por tu organización",
    notPresent: "No está presente en este dispositivo",
  },
  notSupportedOnDevice: "No es compatible con este dispositivo",
  reversible: "Se puede deshacer",
  reversibleWithBackup: "Se puede deshacer desde una copia de seguridad",
  irreversible: (reason: string) => `No se puede deshacer: ${reason}`,
  outcomeInterrupted: "Se interrumpió antes de terminar; estado desconocido",
  outcomeApplied: "Aplicado",
  outcomeAlreadyApplied: "Ya estaba así; no se cambió nada",
  outcomeStateChanged: "Omitido: la configuración cambió después de la revisión",
  outcomeDenied: "Denegado: no se otorgó el permiso de administrador",
  outcomeUnsupported: (reason: string) => `Omitido: ${reason}`,
  outcomeNotAttempted: "No se intentó",
  outcomeFailed: "Falló",
  needsAdministrator: "Requiere administrador",
  rollback: {
    available: "Se puede deshacer",
    alreadyRolledBack: "Ya se deshizo",
    irreversible: "No se puede deshacer",
    interrupted: "Interrumpido; revisa la configuración manualmente",
    nothingApplied: "No hay nada que deshacer",
  },
  resultsLabel: "Resultados de los cambios del sistema",
  allFinished: "Todos los cambios terminaron.",
  someUnfinished: "Algunos cambios no terminaron. Cada resultado indica qué pasó; no se cambió nada más sin avisar.",
  reviewAndApply: "Revisar y aplicar",
  reviewSelected: "Revisar los cambios seleccionados",
  reviewButton: (label: string, count: number) => `${label} (${count})`,
  tooMany: (max: number) => `Selecciona como máximo ${max} cambios a la vez.`,
  checkingState: "Comprobando el estado actual de cada cambio…",
  ticketIntro: (requiresHelper: boolean, seconds: number) =>
    `Estos cambios se harán en orden. Windows te pedirá que confirmes; ${requiresHelper ? "se pedirá permiso de administrador (UAC) una sola vez." : "no se necesita permiso de administrador."} Esta revisión vence en ${seconds} segundos.`,
  continueToWindows: "Continuar a la confirmación de Windows",
  discardReview: "Descartar revisión",
  applying: "Esperando la confirmación de Windows y aplicando…",
  historyTitle: "Historial de cambios",
  historyEmpty: "Todavía no hay cambios registrados.",
  reviewUndo: (count: number) => `Revisar deshacer (${count})`,
  undoIntro: "Deshacer restaura el estado registrado antes de cada cambio. Windows te pedirá que confirmes.",
  errors: {
    confirmationDeclined: "Cancelaste la confirmación de Windows. No se cambió nada.",
    planExpired: "La revisión venció después de 60 segundos. Vuelve a revisar los cambios.",
    planNotFound: "Esta revisión ya no es válida. Vuelve a revisar los cambios.",
    unsupported: "Este cambio no es compatible con este dispositivo.",
    busy: "Todavía se está ejecutando otro cambio del sistema.",
    tooManyChanges: "Selecciona como máximo 32 cambios a la vez.",
    journalUnavailable:
      "No se pudo leer el historial de cambios. Es posible que lo haya escrito una versión más reciente de esta app; actualiza la app o consulta la guía del administrador para restablecerlo.",
    fallback: "No se pudo completar el cambio del sistema.",
  },
} satisfies Catalog<typeof en>;

export const systemChangeStrings = { en, es419 };
export type SystemChangeStrings = typeof en;
