import type { Catalog } from "../../shared/i18n/catalog";
import type { ArtifactRole, BuildEcosystem, BuildRunState, ProtectionReason, RebuildCost } from "./api";

const en = {
  heading: "Build artifact budgets",
  loadingRoots: "Loading project roots…",
  retryRoots: "Retry loading project roots",
  rootsLoadFailed: "Project roots could not be loaded. Profile registration and project overrides are unavailable.",
  operationFailed: "The build artifact operation could not be completed.",
  errors: {
    invalidInput: "The build artifact request was invalid.",
    approvalDeclined: "The native approval was declined.",
    notFound: "The build item is no longer available.",
    buildBusy: "Another build is already running.",
    validationFailed: "The operation stopped because registered build state changed.",
    operationFailed: "The build operation could not be completed.",
    taskUnavailable: "The build task could not be started.",
  },
  analysisFailedAfterSave: "Artifact budgets were saved, but immediate analysis failed. The saved policy remains active.",
  validation: {
    tooManyBytes: (maximum: number) => `Use at most ${maximum} UTF-8 bytes.`,
    enterLabel: "Enter a label.",
    controlCharacters: "Control characters are not allowed.",
    nullCharacters: "Null characters are not allowed.",
    invalidRelativePath: "Enter a relative path without a root, drive prefix, or parent components.",
    overlappingPath: "Artifact paths must not duplicate or overlap another path.",
  },
  settings: {
    loading: "Loading artifact settings…",
    intro: "Disabled by default. Analysis never treats watcher silence as a successful build.",
    enforce: "Enforce artifact budgets",
    enforceHelp: "When off, scheduled analysis and artifact quarantine stop.",
    globalSize: "Global maximum size (GiB)",
    globalSizeHelp: "Leave empty for no global size limit.",
    globalAge: "Global maximum age (days)",
    globalAgeHelp: "Leave empty for no global age limit.",
    interval: "Scheduled analysis interval (hours)",
    grace: "External-change grace (hours)",
    recovery: "Quarantine recovery (days)",
    perProject: "Per-project behavior",
    noRoots: "Add a project root on Cleanup to set a project override.",
    behavior: "Budget behavior",
    modeInherit: "Use global limits",
    modeDisabled: "Disable for this project",
    modeExplicit: "Use project limits",
    maximumSize: "Maximum size (GiB)",
    maximumAge: "Maximum age (days)",
    emptyExplicit: "Enter a maximum size or maximum age for project limits.",
    recoveryNote: "Quarantined generations remain undoable until the recovery period ends.",
    saving: "Saving…",
    save: "Save artifact budgets",
  },
  coordinator: {
    intro: "Run one approved native build, then quarantine only stale owned generations.",
    budgetsEnabled: "Automatic budgets enabled",
    budgetsDisabled: "Automatic budgets disabled",
    noRoots: "No project roots are registered. Add one on Cleanup to register a build profile.",
    registerLegend: "Register a build profile",
    confirmHelp: "Windows confirms the executable, every argument, working directory, and artifact path.",
    labelBytesHelp: (maximum: number) => `Names and labels allow at most ${maximum} UTF-8 bytes each.`,
    profileName: "Profile name",
    projectRoot: "Project root",
    selectRoot: "Select a saved root",
    ecosystem: "Ecosystem",
    ecosystemOptions: { rust: "Rust", node: "Node", generic: "Generic wrapper" } satisfies Record<BuildEcosystem, string>,
    executable: "Native executable (.exe)",
    workingDirectory: "Working directory, relative to root",
    workingDirectoryPlaceholder: "Leave empty for project root",
    profileLabel: "Profile label",
    toolchainLabel: "Toolchain label",
    targetLabel: "Target label",
    rebuildCost: "Rebuild cost",
    rebuildCostOptions: { low: "Low", medium: "Medium", high: "High" } satisfies Record<RebuildCost, string>,
    argumentsLegend: "Arguments, in order",
    argumentsHelp: (maxArguments: number, maxBytes: number) =>
      `Each row is one argument. Maximum ${maxArguments} arguments, ${maxBytes} UTF-8 bytes each. Shell command text is not accepted.`,
    argument: (index: number) => `Argument ${index}`,
    remove: "Remove",
    addArgument: "Add argument",
    artifactsLegend: "Registered artifact paths",
    artifactsHelp: (maximum: number) =>
      `Use up to ${maximum} relative paths, without duplicates or overlaps. Dependencies and incremental state are always protected.`,
    relativePath: (index: number) => `Relative path ${index}`,
    role: "Role",
    roleOptions: { generation: "Generation", dependency: "Dependency", incremental: "Incremental" } satisfies Record<ArtifactRole, string>,
    addArtifactPath: "Add artifact path",
    submit: "Review and register profile",
    latestBuild: (state: string) => `Latest build: ${state}`,
    exitCode: (code: number) => `, exit code ${code}`,
    noRun: "No coordinated build has run in this session.",
    runStates: {
      queued: "queued",
      running: "running",
      succeeded: "succeeded",
      failed: "build failed",
      cancelled: "cancelled",
      analysisFailed: "artifact analysis or budget enforcement failed; completed quarantine moves remain undoable",
    } satisfies Record<BuildRunState, string>,
    savedProfiles: "Saved profiles",
    loadingProfiles: "Loading profiles…",
    noProfiles: "No build profiles are registered.",
    ecosystemValues: { rust: "rust", node: "node", generic: "generic" } satisfies Record<BuildEcosystem, string>,
    detailsFor: (name: string) => `Details for ${name}`,
    details: "Details",
    executableTerm: "Executable",
    noArguments: "No arguments",
    emptyArgument: "Empty argument",
    projectRootSuffix: " (Project root)",
    rebuildCostValues: { low: "low", medium: "medium", high: "high" } satisfies Record<RebuildCost, string>,
    artifactPathsTerm: "Artifact paths, relative to root",
    artifactPathsList: "Artifact paths and roles",
    roleValues: { generation: "generation", dependency: "dependency", incremental: "incremental" } satisfies Record<ArtifactRole, string>,
    run: "Run",
    cancel: "Cancel",
    forget: "Forget",
    forgetHelp: "Forgetting stops future runs and budgets; it does not delete artifacts.",
    budgetPreview: "Budget preview",
    refreshPreview: "Refresh preview",
    current: "Current",
    projected: "Projected",
    quarantine: "Quarantine",
    protectedFloorGlobal: (bytes: string) =>
      `Protected data alone uses ${bytes}. The limit remains unmet without deleting protected state.`,
    perProjectPreview: "Per-project preview",
    modeExplicit: "Explicit project limits",
    modeDisabled: "Disabled for this project",
    modeInherit: "Inherit global limits",
    sizeLimit: "Size limit:",
    ageLimit: "Age limit:",
    noLimit: "None",
    days: (days: number) => `${days} days`,
    protectedFloor: "Protected floor",
    protectedFloorProject: (bytes: string) =>
      `Protected data exceeds this project’s ${bytes} size limit. The limit cannot be met without deleting protected state.`,
    selectedGenerations: "Selected generations",
    nothingSelected: "Nothing is selected for quarantine.",
    protectedGenerations: "Protected generations",
    noProtected: "No protected generations are recorded.",
    reasonSeparator: ", ",
    reasons: {
      unowned: "Not created by an approved build",
      nonGeneration: "Not a removable generation",
      active: "Currently active",
      currentProfile: "Current build profile",
      currentTarget: "Current target",
      dependency: "Dependency output",
      incremental: "Incremental build state",
      latestSuccessfulBuild: "Touched by the latest successful build",
      recentExternalChange: "Changed recently outside the coordinator",
      unreadable: "Could not be read safely",
      ambiguous: "Identity or path is ambiguous",
      missingIdentity: "Stable file identity is unavailable",
    } satisfies Record<ProtectionReason, string>,
  },
};

const es419 = {
  heading: "Presupuestos de artefactos de compilación",
  loadingRoots: "Cargando raíces de proyecto…",
  retryRoots: "Reintentar la carga de raíces de proyecto",
  rootsLoadFailed: "No se pudieron cargar las raíces de proyecto. El registro de perfiles y las excepciones por proyecto no están disponibles.",
  operationFailed: "No se pudo completar la operación de artefactos de compilación.",
  errors: {
    invalidInput: "La solicitud de artefactos de compilación no era válida.",
    approvalDeclined: "Se rechazó la aprobación nativa.",
    notFound: "El elemento de compilación ya no está disponible.",
    buildBusy: "Ya se está ejecutando otra compilación.",
    validationFailed: "La operación se detuvo porque cambió el estado de compilación registrado.",
    operationFailed: "No se pudo completar la operación de compilación.",
    taskUnavailable: "No se pudo iniciar la tarea de compilación.",
  },
  analysisFailedAfterSave: "Los presupuestos de artefactos se guardaron, pero el análisis inmediato falló. La política guardada sigue activa.",
  validation: {
    tooManyBytes: (maximum: number) => `Usa como máximo ${maximum} bytes UTF-8.`,
    enterLabel: "Escribe una etiqueta.",
    controlCharacters: "No se permiten caracteres de control.",
    nullCharacters: "No se permiten caracteres nulos.",
    invalidRelativePath: "Escribe una ruta relativa sin raíz, prefijo de unidad ni componentes de carpeta superior (..).",
    overlappingPath: "Las rutas de artefactos no deben duplicar ni superponerse con otra ruta.",
  },
  settings: {
    loading: "Cargando configuración de artefactos…",
    intro: "Desactivado de forma predeterminada. El análisis nunca considera el silencio del monitor como una compilación correcta.",
    enforce: "Aplicar presupuestos de artefactos",
    enforceHelp: "Si está desactivado, se detienen el análisis programado y la recuperación de la app de artefactos.",
    globalSize: "Tamaño máximo global (GiB)",
    globalSizeHelp: "Déjalo vacío para no tener límite de tamaño global.",
    globalAge: "Antigüedad máxima global (días)",
    globalAgeHelp: "Déjalo vacío para no tener límite de antigüedad global.",
    interval: "Intervalo del análisis programado (horas)",
    grace: "Margen para cambios externos (horas)",
    recovery: "Recuperación de la app (días)",
    perProject: "Comportamiento por proyecto",
    noRoots: "Agrega una raíz de proyecto en Limpieza para definir una excepción por proyecto.",
    behavior: "Comportamiento del presupuesto",
    modeInherit: "Usar límites globales",
    modeDisabled: "Desactivar para este proyecto",
    modeExplicit: "Usar límites del proyecto",
    maximumSize: "Tamaño máximo (GiB)",
    maximumAge: "Antigüedad máxima (días)",
    emptyExplicit: "Escribe un tamaño máximo o una antigüedad máxima para los límites del proyecto.",
    recoveryNote: "Las generaciones en recuperación de la app se pueden deshacer hasta que termine el período de recuperación.",
    saving: "Guardando…",
    save: "Guardar presupuestos de artefactos",
  },
  coordinator: {
    intro: "Ejecuta una compilación nativa aprobada y luego envía a recuperación de la app solo las generaciones propias obsoletas.",
    budgetsEnabled: "Presupuestos automáticos activados",
    budgetsDisabled: "Presupuestos automáticos desactivados",
    noRoots: "No hay raíces de proyecto registradas. Agrega una en Limpieza para registrar un perfil de compilación.",
    registerLegend: "Registrar un perfil de compilación",
    confirmHelp: "Windows confirma el ejecutable, cada argumento, el directorio de trabajo y la ruta de cada artefacto.",
    labelBytesHelp: (maximum: number) => `Los nombres y etiquetas admiten como máximo ${maximum} bytes UTF-8 cada uno.`,
    profileName: "Nombre del perfil",
    projectRoot: "Raíz del proyecto",
    selectRoot: "Selecciona una raíz guardada",
    ecosystem: "Ecosistema",
    ecosystemOptions: { rust: "Rust", node: "Node", generic: "Contenedor genérico" },
    executable: "Ejecutable nativo (.exe)",
    workingDirectory: "Directorio de trabajo, relativo a la raíz",
    workingDirectoryPlaceholder: "Déjalo vacío para usar la raíz del proyecto",
    profileLabel: "Etiqueta del perfil",
    toolchainLabel: "Etiqueta de la cadena de herramientas",
    targetLabel: "Etiqueta del destino",
    rebuildCost: "Costo de recompilación",
    rebuildCostOptions: { low: "Bajo", medium: "Medio", high: "Alto" },
    argumentsLegend: "Argumentos, en orden",
    argumentsHelp: (maxArguments: number, maxBytes: number) =>
      `Cada fila es un argumento. Máximo ${maxArguments} argumentos, ${maxBytes} bytes UTF-8 cada uno. No se acepta texto de comandos de shell.`,
    argument: (index: number) => `Argumento ${index}`,
    remove: "Quitar",
    addArgument: "Agregar argumento",
    artifactsLegend: "Rutas de artefactos registradas",
    artifactsHelp: (maximum: number) =>
      `Usa hasta ${maximum} rutas relativas, sin duplicados ni superposiciones. Las dependencias y el estado incremental siempre están protegidos.`,
    relativePath: (index: number) => `Ruta relativa ${index}`,
    role: "Rol",
    roleOptions: { generation: "Generación", dependency: "Dependencia", incremental: "Incremental" },
    addArtifactPath: "Agregar ruta de artefacto",
    submit: "Revisar y registrar perfil",
    latestBuild: (state: string) => `Última compilación: ${state}`,
    exitCode: (code: number) => `, código de salida ${code}`,
    noRun: "No se ha ejecutado ninguna compilación coordinada en esta sesión.",
    runStates: {
      queued: "en cola",
      running: "en ejecución",
      succeeded: "correcta",
      failed: "la compilación falló",
      cancelled: "cancelada",
      analysisFailed: "falló el análisis de artefactos o la aplicación del presupuesto; los movimientos completados a recuperación de la app se pueden deshacer",
    },
    savedProfiles: "Perfiles guardados",
    loadingProfiles: "Cargando perfiles…",
    noProfiles: "No hay perfiles de compilación registrados.",
    ecosystemValues: { rust: "rust", node: "node", generic: "genérico" },
    detailsFor: (name: string) => `Detalles de ${name}`,
    details: "Detalles",
    executableTerm: "Ejecutable",
    noArguments: "Sin argumentos",
    emptyArgument: "Argumento vacío",
    projectRootSuffix: " (Raíz del proyecto)",
    rebuildCostValues: { low: "bajo", medium: "medio", high: "alto" },
    artifactPathsTerm: "Rutas de artefactos, relativas a la raíz",
    artifactPathsList: "Rutas y roles de artefactos",
    roleValues: { generation: "generación", dependency: "dependencia", incremental: "incremental" },
    run: "Ejecutar",
    cancel: "Cancelar",
    forget: "Olvidar",
    forgetHelp: "Olvidar detiene las ejecuciones y los presupuestos futuros; no elimina artefactos.",
    budgetPreview: "Vista previa del presupuesto",
    refreshPreview: "Actualizar vista previa",
    current: "Actual",
    projected: "Proyectado",
    quarantine: "Recuperación de la app",
    protectedFloorGlobal: (bytes: string) =>
      `Solo los datos protegidos ocupan ${bytes}. El límite sigue sin cumplirse sin eliminar el estado protegido.`,
    perProjectPreview: "Vista previa por proyecto",
    modeExplicit: "Límites explícitos del proyecto",
    modeDisabled: "Desactivado para este proyecto",
    modeInherit: "Heredar límites globales",
    sizeLimit: "Límite de tamaño:",
    ageLimit: "Límite de antigüedad:",
    noLimit: "Ninguno",
    days: (days: number) => (days === 1 ? `${days} día` : `${days} días`),
    protectedFloor: "Mínimo protegido",
    protectedFloorProject: (bytes: string) =>
      `Los datos protegidos superan el límite de tamaño de ${bytes} de este proyecto. El límite no se puede cumplir sin eliminar el estado protegido.`,
    selectedGenerations: "Generaciones seleccionadas",
    nothingSelected: "No hay nada seleccionado para recuperación de la app.",
    protectedGenerations: "Generaciones protegidas",
    noProtected: "No hay generaciones protegidas registradas.",
    reasonSeparator: ", ",
    reasons: {
      unowned: "No la creó una compilación aprobada",
      nonGeneration: "No es una generación eliminable",
      active: "Activa actualmente",
      currentProfile: "Perfil de compilación actual",
      currentTarget: "Destino actual",
      dependency: "Salida de dependencia",
      incremental: "Estado de compilación incremental",
      latestSuccessfulBuild: "Modificada por la última compilación correcta",
      recentExternalChange: "Cambió recientemente fuera del coordinador",
      unreadable: "No se pudo leer de forma segura",
      ambiguous: "La identidad o la ruta es ambigua",
      missingIdentity: "La identidad estable del archivo no está disponible",
    },
  },
} satisfies Catalog<typeof en>;

export const buildArtifactsStrings = { en, es419 };
export type BuildArtifactsStrings = typeof en;
export type BuildArtifactValidationStrings = BuildArtifactsStrings["validation"];
