import type { Catalog } from "../../shared/i18n/catalog";
import type { UpdateErrorCode } from "../../shared/app-settings/updateApi";
import type { LanguagePreference } from "../../shared/i18n/locale";
import type { ScanProfile } from "./api/scanSettings";

const en = {
  documentTitle: "Settings | Supa Diska Klinah",
  kicker: "Preferences",
  heading: "Settings",
  intro: "Cleanup preferences are saved on this device.",
  tryAgain: "Try again",
  saving: "Saving…",
  language: {
    heading: "Language",
    description: "Choose the language for the app and its Windows confirmation dialogs.",
    label: "Display language",
    hint: "System follows the Windows display language. Unsupported languages use English.",
    // Each language is named in itself so people can find their own.
    options: { system: "System (Windows)", en: "English", "es-419": "Español (Latinoamérica)" } satisfies Record<LanguagePreference, string>,
    saveError: "The language could not be saved. The previous language is still in use.",
  },
  updates: {
    heading: "App updates",
    description: "Off by default. When on, the app checks this project's GitHub releases only when you ask. Nothing is downloaded or installed without your confirmation.",
    toggle: "Allow checking for updates",
    toggleHint: "Contacts raw.githubusercontent.com and github.com. No personal data is sent.",
    currentVersion: (version: string) => `Installed version: ${version}`,
    unsignedNote: "Releases are currently not code-signed. Each update is still verified against a signed manifest built into this app before it can run.",
    notConfigured: "Updates are not available in this build.",
    check: "Check for updates",
    checking: "Checking for updates…",
    recovering: "Checking a previous update…",
    upToDate: "You have the latest version.",
    available: (version: string, size: string) => `Version ${version} is available (${size}).`,
    download: "Download and verify",
    downloading: (version: string) => `Downloading and verifying version ${version}…`,
    verified: (version: string) => `Version ${version} is downloaded and verified.`,
    install: "Install update…",
    installHint: "Windows will ask you to confirm. The app closes while the installer runs; your data and settings are kept.",
    launched: (version: string) => `The installer for version ${version} is running.`,
    interrupted: (version: string) => `The update to version ${version} didn't finish. You can try again with the downloaded installer or discard it.`,
    retry: "Try the installation again…",
    discard: "Discard download",
    saveError: "The update setting could not be saved.",
    errors: {
      notConfigured: "Updates are not available in this build.",
      notPermitted: "Turn on update checks first.",
      busy: "Another update step is still running.",
      network: "Couldn't reach the update server. Check your connection and try again.",
      badManifest: "The update information failed its security check and was ignored.",
      noUpdateChecked: "Check for updates first.",
      downloadFailed: "The download didn't finish. Try again.",
      integrityFailed: "The downloaded file didn't match the signed update and was deleted.",
      signatureRejected: "The installer's Windows signature didn't meet the update policy and was deleted.",
      storage: "The update couldn't be saved on this device.",
      nothingToInstall: "There is no verified update to install.",
      declined: "Installation cancelled. Nothing was changed.",
      launchFailed: "Windows couldn't start the installer. Try again.",
      invalidResponse: "The update status couldn't be read.",
    } satisfies Record<UpdateErrorCode | "invalidResponse", string>,
  },
  autoCleanup: {
    heading: "Automatic cleanup",
    description: "When enabled, eligible temporary caches enter app-managed quarantine at startup.",
    loading: "Loading cleanup settings…",
    loadError: "Cleanup settings could not be loaded.",
    enabledLabel: "Clean temporary caches at startup",
    enabledHint: "Off by default. Disabling stops future quarantine and purge.",
    graceLabel: "Recovery grace period",
    graceHint: "Quarantined items remain undoable until this period ends.",
    graceDays: (days: number) => `${days} ${days === 1 ? "day" : "days"}`,
    purgeNote: "Due quarantine is permanently purged during a later startup maintenance pass.",
    saveError: "Cleanup settings could not be saved. Your changes remain unsaved.",
    saved: "Cleanup settings saved.",
    save: "Save changes",
  },
  scanSpeed: {
    heading: "Scan speed",
    description:
      "Currently speeds up only build-artifact discovery in project cleanup. Other scans, such as Large files and Disk analyzer, read one folder at a time, so this setting does not change them.",
    loading: "Loading scan settings…",
    loadError: "Scan settings could not be loaded.",
    driveType: "Drive type",
    profiles: {
      auto: "Automatic (recommended)",
      ssd: "Solid-state drive",
      hdd: "Hard drive",
    } satisfies Record<ScanProfile, string>,
    hints: {
      auto: "Checks each drive. Build-artifact discovery on solid-state drives searches more folders at once; hard drives and unknown drives keep the standard amount.",
      ssd: "Build-artifact discovery always searches more folders at once. Fastest on SSD and NVMe drives.",
      hdd: "Build-artifact discovery always searches the standard number of folders at once. Avoids extra disk seeking on spinning drives.",
    } satisfies Record<ScanProfile, string>,
    appliesNote: "Applies to the next build-artifact discovery you start.",
    saveError: "Scan settings could not be saved. Your change remains unsaved.",
    saved: "Scan settings saved.",
    save: "Save scan settings",
  },
};

const es419 = {
  documentTitle: "Configuración | Supa Diska Klinah",
  kicker: "Preferencias",
  heading: "Configuración",
  intro: "Las preferencias de limpieza se guardan en este dispositivo.",
  tryAgain: "Intentar de nuevo",
  saving: "Guardando…",
  language: {
    heading: "Idioma",
    description: "Elige el idioma de la app y de sus cuadros de confirmación de Windows.",
    label: "Idioma de la interfaz",
    hint: "Sistema sigue el idioma de Windows. Los idiomas no disponibles usan inglés.",
    options: { system: "Sistema (Windows)", en: "English", "es-419": "Español (Latinoamérica)" },
    saveError: "No se pudo guardar el idioma. Se sigue usando el idioma anterior.",
  },
  updates: {
    heading: "Actualizaciones de la app",
    description: "Desactivado de forma predeterminada. Cuando está activado, la app consulta las versiones de GitHub de este proyecto solo cuando tú lo pides. No se descarga ni se instala nada sin tu confirmación.",
    toggle: "Permitir buscar actualizaciones",
    toggleHint: "Se conecta con raw.githubusercontent.com y github.com. No se envían datos personales.",
    currentVersion: (version: string) => `Versión instalada: ${version}`,
    unsignedNote: "Por ahora, las versiones no tienen firma de código. Aun así, cada actualización se verifica con un manifiesto firmado incluido en esta app antes de poder ejecutarse.",
    notConfigured: "Las actualizaciones no están disponibles en esta compilación.",
    check: "Buscar actualizaciones",
    checking: "Buscando actualizaciones…",
    recovering: "Revisando una actualización anterior…",
    upToDate: "Tienes la versión más reciente.",
    available: (version: string, size: string) => `La versión ${version} está disponible (${size}).`,
    download: "Descargar y verificar",
    downloading: (version: string) => `Descargando y verificando la versión ${version}…`,
    verified: (version: string) => `La versión ${version} está descargada y verificada.`,
    install: "Instalar actualización…",
    installHint: "Windows te pedirá que confirmes. La app se cierra mientras se ejecuta el instalador; tus datos y tu configuración se conservan.",
    launched: (version: string) => `El instalador de la versión ${version} se está ejecutando.`,
    interrupted: (version: string) => `La actualización a la versión ${version} no terminó. Puedes volver a intentarlo con el instalador descargado o descartarlo.`,
    retry: "Volver a intentar la instalación…",
    discard: "Descartar descarga",
    saveError: "No se pudo guardar la configuración de actualizaciones.",
    errors: {
      notConfigured: "Las actualizaciones no están disponibles en esta compilación.",
      notPermitted: "Primero activa la búsqueda de actualizaciones.",
      busy: "Todavía se está ejecutando otro paso de la actualización.",
      network: "No se pudo conectar con el servidor de actualizaciones. Revisa tu conexión y vuelve a intentarlo.",
      badManifest: "La información de la actualización no pasó la verificación de seguridad y se ignoró.",
      noUpdateChecked: "Primero busca actualizaciones.",
      downloadFailed: "La descarga no terminó. Vuelve a intentarlo.",
      integrityFailed: "El archivo descargado no coincidía con la actualización firmada y se eliminó.",
      signatureRejected: "La firma de Windows del instalador no cumplía la política de actualizaciones y se eliminó.",
      storage: "No se pudo guardar la actualización en este dispositivo.",
      nothingToInstall: "No hay ninguna actualización verificada para instalar.",
      declined: "Instalación cancelada. No se cambió nada.",
      launchFailed: "Windows no pudo iniciar el instalador. Vuelve a intentarlo.",
      invalidResponse: "No se pudo leer el estado de la actualización.",
    },
  },
  autoCleanup: {
    heading: "Limpieza automática",
    description:
      "Cuando está activada, las cachés temporales aptas pasan a la recuperación de la app al iniciar.",
    loading: "Cargando la configuración de limpieza…",
    loadError: "No se pudo cargar la configuración de limpieza.",
    enabledLabel: "Limpiar cachés temporales al iniciar",
    enabledHint:
      "Desactivada de forma predeterminada. Al desactivarla se detienen futuros envíos a la recuperación de la app y su eliminación definitiva.",
    graceLabel: "Periodo de gracia para recuperar",
    graceHint: "Los elementos en recuperación de la app se pueden deshacer hasta que termine este periodo.",
    graceDays: (days: number) => `${days} ${days === 1 ? "día" : "días"}`,
    purgeNote:
      "Los elementos vencidos en la recuperación de la app se eliminan permanentemente durante un mantenimiento posterior al iniciar.",
    saveError: "No se pudo guardar la configuración de limpieza. Tus cambios siguen sin guardar.",
    saved: "Configuración de limpieza guardada.",
    save: "Guardar cambios",
  },
  scanSpeed: {
    heading: "Velocidad de análisis",
    description:
      "Por ahora solo acelera la detección de artefactos de compilación en la limpieza de proyectos. Otros análisis, como Archivos grandes y Analizador de disco, leen una carpeta a la vez, así que esta opción no los cambia.",
    loading: "Cargando la configuración de análisis…",
    loadError: "No se pudo cargar la configuración de análisis.",
    driveType: "Tipo de unidad",
    profiles: {
      auto: "Automático (recomendado)",
      ssd: "Unidad de estado sólido",
      hdd: "Disco duro",
    },
    hints: {
      auto: "Revisa cada unidad. En unidades de estado sólido, la detección de artefactos de compilación busca en más carpetas a la vez; los discos duros y las unidades desconocidas mantienen la cantidad estándar.",
      ssd: "La detección de artefactos de compilación siempre busca en más carpetas a la vez. Es lo más rápido en unidades SSD y NVMe.",
      hdd: "La detección de artefactos de compilación siempre busca en la cantidad estándar de carpetas a la vez. Evita búsquedas adicionales del disco en unidades mecánicas.",
    },
    appliesNote: "Se aplica a la próxima detección de artefactos de compilación que inicies.",
    saveError: "No se pudo guardar la configuración de análisis. Tu cambio sigue sin guardar.",
    saved: "Configuración de análisis guardada.",
    save: "Guardar configuración de análisis",
  },
} satisfies Catalog<typeof en>;

export const settingsStrings = { en, es419 };
export type SettingsStrings = typeof en;
