import type { Catalog } from "../../shared/i18n/catalog";
import type { Edition } from "./types";

const en = {
  edition: {
    home: "Home", pro: "Pro", education: "Education", enterprise: "Enterprise", server: "Server", other: "Other",
  } satisfies Record<Edition, string>,
  unknown: "Unknown",
  yes: "Yes",
  no: "No",
  windowsDefault: "Windows default",
  days: (value: number) => `${value} days`,
  loadError: "Windows Update status could not be read.",
  detectError: "Windows could not start an update check.",
  describePolicy: (label: string, value: string) => `Set Windows Update policy: ${label} → ${value}`,
  describePolicyId: (id: string) => `Set Windows Update policy: ${id}`,
  eyebrow: "System",
  title: "Windows Update",
  intro: "Shows what the Windows Update Agent reports and lets you set a few documented Group Policy values; checking for updates never installs anything by itself.",
  refresh: "Refresh",
  checkNow: "Check for updates now",
  loading: "Reading Windows Update status…",
  detecting: "Asking Windows to check for updates…",
  detectStarted: "Windows started checking for updates in the background. Results appear in Settings › Windows Update; refresh this page in a few minutes to see the last search time.",
  apiAvailable: "Windows Update API available",
  serviceEnabled: "Automatic Updates service enabled",
  lastSearch: "Last successful search",
  lastInstall: "Last successful install",
  rebootRequired: "Restart required",
  editionLabel: "Edition",
  managed: "Managed by an organization",
  policiesTitle: "Update policies",
  policiesUnavailable: (reason: string) => `Policy changes are unavailable: ${reason}.`,
  policyValueFor: (label: string) => `Policy value for ${label}`,
  current: (value: string) => `Current: ${value}`,
  notApplied: " (not applied on this device)",
  unlisted: (value: number) => `Unlisted value (${value})`,
  rangeHint: (min: number, max: number) => `Leave empty for Windows default. Allowed: ${min}–${max} days.`,
  rangeError: (min: number, max: number) => `Enter a whole number from ${min} to ${max}.`,
};

const es419 = {
  edition: {
    home: "Home", pro: "Pro", education: "Education", enterprise: "Enterprise", server: "Server", other: "Otra",
  },
  unknown: "Desconocido",
  yes: "Sí",
  no: "No",
  windowsDefault: "Predeterminado de Windows",
  days: (value: number) => `${value} días`,
  loadError: "No se pudo leer el estado de Windows Update.",
  detectError: "Windows no pudo iniciar una búsqueda de actualizaciones.",
  describePolicy: (label: string, value: string) => `Establecer directiva de Windows Update: ${label} → ${value}`,
  describePolicyId: (id: string) => `Establecer directiva de Windows Update: ${id}`,
  eyebrow: "Sistema",
  title: "Windows Update",
  intro: "Muestra lo que informa el Agente de Windows Update y te permite establecer algunos valores documentados de directiva de grupo; buscar actualizaciones nunca instala nada por sí solo.",
  refresh: "Actualizar",
  checkNow: "Buscar actualizaciones ahora",
  loading: "Leyendo el estado de Windows Update…",
  detecting: "Pidiendo a Windows que busque actualizaciones…",
  detectStarted: "Windows comenzó a buscar actualizaciones en segundo plano. Los resultados aparecen en Configuración › Windows Update; actualiza esta página en unos minutos para ver la hora de la última búsqueda.",
  apiAvailable: "API de Windows Update disponible",
  serviceEnabled: "Servicio de actualizaciones automáticas habilitado",
  lastSearch: "Última búsqueda correcta",
  lastInstall: "Última instalación correcta",
  rebootRequired: "Requiere reinicio",
  editionLabel: "Edición",
  managed: "Administrado por una organización",
  policiesTitle: "Directivas de actualización",
  policiesUnavailable: (reason: string) => `Los cambios de directiva no están disponibles: ${reason}.`,
  policyValueFor: (label: string) => `Valor de directiva para ${label}`,
  current: (value: string) => `Actual: ${value}`,
  notApplied: " (no se aplica en este dispositivo)",
  unlisted: (value: number) => `Valor no incluido en la lista (${value})`,
  rangeHint: (min: number, max: number) => `Déjalo vacío para usar el valor predeterminado de Windows. Permitido: ${min}–${max} días.`,
  rangeError: (min: number, max: number) => `Escribe un número entero de ${min} a ${max}.`,
} satisfies Catalog<typeof en>;

export const updatesStrings = { en, es419 };
export type UpdatesStrings = typeof en;
