import type { Catalog } from "../../shared/i18n/catalog";
import type { FirewallAction, FirewallProfile, RuleDirection } from "./types";

const en = {
  profile: { domain: "Domain", private: "Private", public: "Public" } satisfies Record<FirewallProfile, string>,
  action: { allow: "Allow", block: "Block", unknown: "Unknown" } satisfies Record<FirewallAction, string>,
  direction: { inbound: "inbound", outbound: "outbound", unknown: "unknown" } satisfies Record<RuleDirection, string>,
  describeRule: (enabled: boolean, rule: string) => `${enabled ? "Turn on" : "Turn off"} firewall rule: ${rule}`,
  describeProfile: (enabled: boolean, profile: string) => `${enabled ? "Turn on" : "Turn off"} ${profile} firewall profile`,
  loadError: "The firewall status could not be read.",
  all: "All",
  none: "None",
  any: "Any",
  eyebrow: "System",
  title: "Firewall",
  intro: "Shows Windows Firewall profiles, notable rules and audit findings; nothing changes until you review and confirm in Windows.",
  refresh: "Refresh",
  loading: "Reading firewall status…",
  profilesTitle: "Profiles",
  on: "On",
  off: "Off",
  active: " (active)",
  inboundDefault: (action: string) => ` · Inbound default: ${action}`,
  outboundDefault: (action: string) => ` · Outbound default: ${action}`,
  blocksAllInbound: " · Blocks all inbound",
  changeProfile: (profile: string, on: boolean) => `Change ${profile} to ${on ? "on" : "off"}`,
  highRisk: "High risk:",
  profileOffWarning: (profiles: string) =>
    ` turning off the ${profiles} firewall profile leaves this PC open to unsolicited network traffic on those networks.`,
  findingsTitle: "Findings",
  noFindings: "No findings.",
  ruleNotFound: "Rule not found in the listed rules",
  ruleAlreadyOff: "Rule is already off",
  turnOffRule: (rule: string) => `Turn off rule ${rule}`,
  rulesTitle: "Rules",
  rulesSummary: (count: string, truncatedAt: string | null, visible: string, matching: string, max: string) =>
    `${count} rules${truncatedAt !== null ? `; only the first ${truncatedAt} were read` : ""}. Showing ${visible} of ${matching} matching (at most ${max}).`,
  filterRules: "Filter rules",
  columns: {
    change: "Change",
    name: "Name",
    state: "State",
    direction: "Direction",
    action: "Action",
    profiles: "Profiles",
    program: "Program",
    localPorts: "Local ports",
    remoteAddresses: "Remote addresses",
  },
  toggleRule: (on: boolean, rule: string) => `Turn ${on ? "on" : "off"} rule ${rule}`,
};

const es419 = {
  profile: { domain: "Dominio", private: "Privado", public: "Público" },
  action: { allow: "Permitir", block: "Bloquear", unknown: "Desconocida" },
  direction: { inbound: "entrada", outbound: "salida", unknown: "desconocida" },
  describeRule: (enabled: boolean, rule: string) => `${enabled ? "Activar" : "Desactivar"} regla del firewall: ${rule}`,
  describeProfile: (enabled: boolean, profile: string) => `${enabled ? "Activar" : "Desactivar"} el perfil ${profile} del firewall`,
  loadError: "No se pudo leer el estado del firewall.",
  all: "Todos",
  none: "Ninguno",
  any: "Cualquiera",
  eyebrow: "Sistema",
  title: "Firewall",
  intro: "Muestra los perfiles del Firewall de Windows, las reglas destacadas y los hallazgos de auditoría; nada cambia hasta que revises y confirmes en Windows.",
  refresh: "Actualizar",
  loading: "Leyendo el estado del firewall…",
  profilesTitle: "Perfiles",
  on: "Activado",
  off: "Desactivado",
  active: " (activo)",
  inboundDefault: (action: string) => ` · Entrada predeterminada: ${action}`,
  outboundDefault: (action: string) => ` · Salida predeterminada: ${action}`,
  blocksAllInbound: " · Bloquea todo el tráfico entrante",
  changeProfile: (profile: string, on: boolean) => `Cambiar ${profile} a ${on ? "activado" : "desactivado"}`,
  highRisk: "Riesgo alto:",
  profileOffWarning: (profiles: string) =>
    ` desactivar el perfil ${profiles} del firewall deja esta PC expuesta a tráfico de red no solicitado en esas redes.`,
  findingsTitle: "Hallazgos",
  noFindings: "No hay hallazgos.",
  ruleNotFound: "La regla no está en la lista de reglas",
  ruleAlreadyOff: "La regla ya está desactivada",
  turnOffRule: (rule: string) => `Desactivar la regla ${rule}`,
  rulesTitle: "Reglas",
  rulesSummary: (count: string, truncatedAt: string | null, visible: string, matching: string, max: string) =>
    `${count} reglas${truncatedAt !== null ? `; solo se leyeron las primeras ${truncatedAt}` : ""}. Se muestran ${visible} de ${matching} coincidencias (como máximo ${max}).`,
  filterRules: "Filtrar reglas",
  columns: {
    change: "Cambio",
    name: "Nombre",
    state: "Estado",
    direction: "Dirección",
    action: "Acción",
    profiles: "Perfiles",
    program: "Programa",
    localPorts: "Puertos locales",
    remoteAddresses: "Direcciones remotas",
  },
  toggleRule: (on: boolean, rule: string) => `${on ? "Activar" : "Desactivar"} la regla ${rule}`,
} satisfies Catalog<typeof en>;

export const firewallStrings = { en, es419 };
export type FirewallStrings = typeof en;
