[package]
name = "privileged-helper"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[[bin]]
name = "privileged-helper"
path = "src/main.rs"
test = false
bench = false

[dependencies]
windows-platform = { path = "../windows-platform" }

[build-dependencies]
winresource = "=0.1.31"
