import type { Catalog } from "../i18n/catalog";

const en = {
  // The product name is a proper noun and is never translated.
  productName: "Supa Diska Klinah",
  brandMark: "S",
  skipToContent: "Skip to content",
  brandSubtitle: "Windows foundation",
  primaryNavigation: "Primary navigation",
  nav: {
    dashboard: "Dashboard",
    drives: "Drives",
    diskAnalyzer: "Disk analyzer",
    largeFiles: "Large files",
    duplicates: "Duplicate files",
    emptyFolders: "Empty folders",
    cleaner: "Rule cleaner",
    browser: "Browser caches",
    uninstaller: "Installed programs",
    cleanup: "Cleanup",
    optimizer: "Quick optimization",
    startup: "Startup apps",
    services: "Windows services",
    privacy: "Privacy",
    firewall: "Firewall",
    hosts: "Hosts file",
    power: "Power and hibernation",
    drivers: "Driver packages",
    restorePoints: "Restore points",
    windowsUpdate: "Windows Update",
    scheduledScans: "Scheduled scans",
    protection: "Protection",
    settings: "Settings",
  },
  updateNotice: {
    updated: (version: string) => `Supa Diska Klinah was updated to version ${version}.`,
    interrupted: (version: string) => `Update didn't finish. The installer for version ${version} is still downloaded and verified. You can try again or discard it in Settings.`,
    discarded: "A downloaded update no longer passed verification, so it was deleted. Nothing was installed.",
    openSettings: "Open Settings",
    dismiss: "Dismiss",
  },
};

const es419 = {
  productName: "Supa Diska Klinah",
  brandMark: "S",
  skipToContent: "Saltar al contenido",
  brandSubtitle: "Base para Windows",
  primaryNavigation: "Navegación principal",
  nav: {
    dashboard: "Panel",
    drives: "Unidades",
    diskAnalyzer: "Analizador de disco",
    largeFiles: "Archivos grandes",
    duplicates: "Archivos duplicados",
    emptyFolders: "Carpetas vacías",
    cleaner: "Limpiador por reglas",
    browser: "Cachés del navegador",
    uninstaller: "Programas instalados",
    cleanup: "Limpieza",
    optimizer: "Optimización rápida",
    startup: "Aplicaciones de inicio",
    services: "Servicios de Windows",
    privacy: "Privacidad",
    firewall: "Firewall",
    hosts: "Archivo hosts",
    power: "Energía e hibernación",
    drivers: "Paquetes de controladores",
    restorePoints: "Puntos de restauración",
    windowsUpdate: "Windows Update",
    scheduledScans: "Análisis programados",
    protection: "Protección",
    settings: "Configuración",
  },
  updateNotice: {
    updated: (version: string) => `Supa Diska Klinah se actualizó a la versión ${version}.`,
    interrupted: (version: string) => `La actualización no terminó. El instalador de la versión ${version} sigue descargado y verificado. Puedes volver a intentarlo o descartarlo en Configuración.`,
    discarded: "Una actualización descargada ya no pasó la verificación, así que se eliminó. No se instaló nada.",
    openSettings: "Abrir Configuración",
    dismiss: "Descartar aviso",
  },
} satisfies Catalog<typeof en>;

export const layoutStrings = { en, es419 };
export type LayoutStrings = typeof en;
