import type { Catalog } from "../../shared/i18n/catalog";

const en = {
  eyebrow: "Catalog-based cleanup",
  title: "Rule cleaner",
  intro: "Choose one native scope, authorize it, then scan. Nothing is selected automatically. Work across roots is sequential, with separate snapshots and plans, not atomic.",
  refreshScopes: "Refresh native scopes",
  loading: "Loading native catalog and scopes…",
  categoryLabel: "Catalog category",
  allCategories: "All categories",
  categoryNote: "This filter changes the catalog display only, not native scan rules. Changing it clears the current scope and results.",
  scopesLegend: "Native scopes",
  scopesNote: "Unavailable or unsupported targets cannot be selected. Paths are display-only; no typed paths are accepted.",
  scopeUnavailable: "Unavailable or unsupported",
  scopePagesLabel: "Native scope pages",
  previousScopes: "Previous scopes",
  nextScopes: "Next scopes",
  scopeCount: (count: string) => `${count} native scope entries; up to 20 shown`,
  selectedScope: (label: string) => `Selected scope: ${label}`,
  catalogSummary: "Catalog rules, provenance and exclusions",
  catalogNote: "This is the compiled catalog inventory, not per-file rule attribution or a claim that each target exists. Scan rows do not provide rule metadata.",
  pathTemplate: (path: string) => `Path template: ${path}`,
  ruleFacts: (seconds: string, version: string, matcher: string) => `Minimum age: ${seconds} seconds · Rule version ${version} · Matcher: ${matcher}`,
  sourceRevision: (source: string, revision: string) => `Source: ${source} · Revision: ${revision}`,
  consequence: (text: string) => `Consequence: ${text}`,
  exclusions: (list: string) => `Exclusions: ${list}`,
  unsupported: (reason: string) => `Unsupported: ${reason}`,
  rulePagesLabel: "Catalog rule pages",
  previousRules: "Previous rules",
  nextRules: "Next rules",
  ruleCount: (count: string) => `${count} catalog rules; up to 20 shown`,
  unsupportedOperation: (operation: string, reason: string) => `Unsupported operation: ${operation}: ${reason}`,
  authorize: "Authorize selected scope",
  authorizedScope: (path: string) => `Authorized scope: ${path}`,
  scan: "Scan cleaner scope",
  singleUse: "Authorization is single-use. Authorize again for another scan. Switching scopes releases old authority and results.",
  resultsCaveat: "Results may omit protected, inaccessible, changing or limit-excluded files. Byte totals are not reclaimed space.",
  selected: (count: string, max: string) => `${count} selected (maximum ${max}).`,
  clearSelection: "Clear selection",
  resultsLabel: "Cleaner results",
  logical: (bytes: string) => `${bytes} logical`,
  unknownAllocation: "Unknown allocation",
  allocated: (bytes: string) => `${bytes} allocated`,
  notSelectable: (reason: string) => `Not selectable: ${reason}`,
  readOnly: "Read-only",
  noMatches: "No matching files on this page.",
  dispositionNote: "App recovery is the default: same-volume storage for manual undo, no space reclaimed and no automatic purge. Permanent deletion is optional and requires Windows confirmation. Windows Recycle Bin is unsupported; there is no path-based fallback.",
};

const es419 = {
  eyebrow: "Limpieza basada en catálogo",
  title: "Limpiador por reglas",
  intro: "Elige un alcance nativo, autorízalo y luego analiza. No se selecciona nada automáticamente. El trabajo entre raíces es secuencial, con instantáneas y planes separados, no atómico.",
  refreshScopes: "Actualizar alcances nativos",
  loading: "Cargando el catálogo y los alcances nativos…",
  categoryLabel: "Categoría del catálogo",
  allCategories: "Todas las categorías",
  categoryNote: "Este filtro solo cambia la vista del catálogo, no las reglas nativas de análisis. Cambiarlo borra el alcance y los resultados actuales.",
  scopesLegend: "Alcances nativos",
  scopesNote: "Los destinos no disponibles o no compatibles no se pueden seleccionar. Las rutas son solo informativas; no se aceptan rutas escritas.",
  scopeUnavailable: "No disponible o no compatible",
  scopePagesLabel: "Páginas de alcances nativos",
  previousScopes: "Alcances anteriores",
  nextScopes: "Alcances siguientes",
  scopeCount: (count: string) => `${count} entradas de alcance nativo; se muestran hasta 20`,
  selectedScope: (label: string) => `Alcance seleccionado: ${label}`,
  catalogSummary: "Reglas del catálogo, procedencia y exclusiones",
  catalogNote: "Este es el inventario compilado del catálogo, no una atribución de reglas por archivo ni una afirmación de que cada destino existe. Las filas del análisis no incluyen metadatos de reglas.",
  pathTemplate: (path: string) => `Plantilla de ruta: ${path}`,
  ruleFacts: (seconds: string, version: string, matcher: string) => `Antigüedad mínima: ${seconds} segundos · Versión de la regla ${version} · Comparador: ${matcher}`,
  sourceRevision: (source: string, revision: string) => `Origen: ${source} · Revisión: ${revision}`,
  consequence: (text: string) => `Consecuencia: ${text}`,
  exclusions: (list: string) => `Exclusiones: ${list}`,
  unsupported: (reason: string) => `No compatible: ${reason}`,
  rulePagesLabel: "Páginas de reglas del catálogo",
  previousRules: "Reglas anteriores",
  nextRules: "Reglas siguientes",
  ruleCount: (count: string) => `${count} reglas del catálogo; se muestran hasta 20`,
  unsupportedOperation: (operation: string, reason: string) => `Operación no compatible: ${operation}: ${reason}`,
  authorize: "Autorizar el alcance seleccionado",
  authorizedScope: (path: string) => `Alcance autorizado: ${path}`,
  scan: "Analizar el alcance del limpiador",
  singleUse: "La autorización es de un solo uso. Vuelve a autorizar para otro análisis. Cambiar de alcance libera la autorización y los resultados anteriores.",
  resultsCaveat: "Los resultados pueden omitir archivos protegidos, inaccesibles, que están cambiando o excluidos por límites. Los totales de bytes no son espacio recuperado.",
  selected: (count: string, max: string) => `${count} seleccionados (máximo ${max}).`,
  clearSelection: "Borrar selección",
  resultsLabel: "Resultados del limpiador",
  logical: (bytes: string) => `${bytes} lógicos`,
  unknownAllocation: "Asignación desconocida",
  allocated: (bytes: string) => `${bytes} asignados`,
  notSelectable: (reason: string) => `No seleccionable: ${reason}`,
  readOnly: "Solo lectura",
  noMatches: "No hay archivos coincidentes en esta página.",
  dispositionNote: "La recuperación de la app es la opción predeterminada: almacenamiento en el mismo volumen para deshacer manualmente, sin recuperar espacio y sin purga automática. La eliminación permanente es opcional y requiere la confirmación de Windows. La Papelera de reciclaje de Windows no es compatible; no hay alternativa basada en rutas.",
} satisfies Catalog<typeof en>;

export const cleanerStrings = { en, es419 };
export type CleanerStrings = typeof en;
